### ISSUE TITLE
Imunity

### ISSUE THREAD

**Issue by DevOpsAmph** [elemental-lf/benji#117]
Air-gapping backups here - I wonder wether it might be interesting to introduce an "Immunity" addition to "Protect". The idea:
- Store the retention policy by ceph storage pool (or further storage modules).
- By default set every valid version to not be modifyable nor deleteable unless it´s aged so much - it would be deleted by the next retention policy enforcement + cleanup anyway. 
- That would freeze things for a periode of time and goes ahead of what the protecion feature offers until now.

**Comment by elemental-lf** [comment]
There already is `disallowRemoveWhenYounger` which is a global setting, see http://benji-backup.me/configuration.html#top-level-configuration-directives.

**Comment by elemental-lf** [comment]
@DevOpsAmph I was about to close this, but I wanted to add that you can define retention policies only for a certain subset of versions. `benji enforce` accepts a filter expression which determines the versions that the policy is applied to. So you could apply a policy to only the versions in a specific storage, to versions of a certain age or by setting labels and filtering on them you could define your own criteria. But `disallowRemoveWhenYounger` is a global thing. Maybe you could give some more detaisl about your use case, I think I have not yet understood your intention.

**Comment by elemental-lf** [comment]
The user didn't respond with details about his use case. I'm going to close this.
