### ISSUE TITLE
nbd-client documentation bug

### ISSUE THREAD

**Issue by jsm222** [elemental-lf/benji#120]
sudo nbd-client -p 10809 -b 512 -t 10 -N V0000000001 127.0.0.1  /dev/nbd0 should at least on Debian 11 (nbd 3.18)  be
sudo nbd-client -p -N V0000000001 localhost 10809 /dev/nbd0 since -p does not mean port number.
from man nbd-client
> -p     When this option is specified, nbd-client will immediately try to reconnect an nbd device if the connection ever drops unexpectedly due to a lost server or something similar.

Great tool BTW :+1:

**Comment by elemental-lf** [comment]
Thank you for pointing this out. I'm going to correct this.
