### ISSUE TITLE
helpers/ceph.py requires pool is 'rbd'

### ISSUE THREAD

**Issue by jsm222** [elemental-lf/benji#121]
Using benji.helpers.ceph.backup your pool must be called rbd
since the scheme is the pool name https://github.com/elemental-lf/benji/blob/6cd0eefcfff0572643f6b77999b4e1511f939d77/src/benji/helpers/ceph.py#L117

https://github.com/elemental-lf/benji/blob/6cd0eefcfff0572643f6b77999b4e1511f939d77/src/benji/helpers/ceph.py#L78
.

my local fix is to hardcode 'rbd' as scheme

**Comment by elemental-lf** [comment]
Hmm, you can rename your instance of the RBD i/o module in your `benji.conf` to match your pool name. Note that this is just a convention that `ceph.py` uses, the scheme doesn't have to match the pool name. It can be helpful in the case where different credentials or configurations are needed for different pools but it has its limitations when multiple clusters with overlapping pool names are involved. 

@jsm222 do you still see a problem here after my clarification?

**Comment by jsm222** [comment]
Oh I see, I thought of the "rbd" as a scheme it is of course the name of the module,which knows that it is of type rbd. So no problem, thanks for clarifying.
