### ISSUE TITLE
add support backup rbd not in default namespace.

### ISSUE THREAD

**Issue by jpsn123** [elemental-lf/benji#122]
**Is your feature request related to a problem? Please describe.**
for now benji just can backup rbd without namespace, but my rbd images are distributed in different namespaces.
`benji backup rbd:pool_name/namespace_name/image_name@snap1 database` cant work.

**Additional context**
I checked the ceph documentation, RBD python interface don't provide namespace parameter.

**Comment by elemental-lf** [comment]
Thanks for the feature request. I just had a look at the Ceph source code and I suspect that the namespace is passed to `librbd` as part of the image name so there is no extra parameter for it. So it might be as easy as adjusting the regular expressions in `src/benji/io/rbd.py`.

**Comment by elemental-lf** [comment]
FYI: PR #126 contains support for RADOS namespaces and I'll try to integrate the changes in the near future.

**Comment by elemental-lf** [comment]
Okay, I looked at this issue before seeing the PR you submitted that contains support for them. My apologies.

**Comment by elemental-lf** [comment]
Base on your PR #126 support for namespaces is now included in the `master` branch. Thanks!
