### ISSUE TITLE
How can I use push gateway with the ceph.sh script.

### ISSUE THREAD

**Issue by devopstales** [elemental-lf/benji#129]
In the old versions with ceph.sh I can send data to a push gateway. In the documentation there is no mention how can I do tat. I find hints it working in the helm chart deployment. Is this working with a standard cli backup, docker environment or just if I backup pvcs?

**Comment by elemental-lf** [comment]
This only works if you use the [k8s-tools](https://github.com/elemental-lf/benji/tree/master/images/benji-k8s/k8s-tools) to call Benji and it will automatically be enabled if Benji is deployed via the Helm Chart. The shell script example doesn't include such support anymore. It did in the past before the move to Python. The old shell scripts are still accessible [here](https://github.com/elemental-lf/benji/tree/v0.6.0/scripts), maybe you can use them as a starting point for your own scripts.

**Comment by elemental-lf** [comment]
I'm going to close this issue because there was no further feedback from the user.
