### ISSUE TITLE
How to build deb package

### ISSUE THREAD

**Issue by div8cn** [elemental-lf/benji#130]
Benji is a project that runs very well under ubuntu, but it needs to be built every time it is installed.
If it can be made into a deb package, it will greatly improve the deployment efficiency;
I know that the benji project has a docker image, but I prefer it to run in non-docker mode

**Comment by elemental-lf** [comment]
Thank you for your suggestion. I think you aren't the first user with this request. I'm using the container images myself so this isn't a priority for me but I'd accept patches to add the necessary files for Debian packaging just like we already have a spec file for building an RPM. 

I'm going to close this issue for now but I'd be happy to look at any PRs adding support for Debian packages.
