### ISSUE TITLE
Add support for arm64

### ISSUE THREAD

**Issue by tbouska** [elemental-lf/benji#131]
I'm running a cluster of arm64 raspberries and I'd like to use benji to backup rook-ceph pvcs. I installed it using helm and benji-maint pod fails to start due to `exec user process caused: exec format error`.

When reading Dockerfile of benji-k8s, I noticed that kubectl amd64 binary is downloaded. I assume this could be the root cause, because centos base image is multi-arch and therefore shouldn't be an issue.

Unfortunately, I lack the skills to patch the Dockerfile and submit a pull request. Can you please check?

Thank you!

**Comment by elemental-lf** [comment]
Yes, as you correctly observed there are no container images for `arm64`. I'm only using the `amd64` platform and as such I most likely won't work on adding support for `arm64`. I'd be happy to review any PRs though.

I'm going to close this issue for now but I've added your suggestion to the TODO list.
