### ISSUE TITLE
Migrate from sqlite3 to postgresql possible?

### ISSUE THREAD

**Issue by fxkai** [elemental-lf/benji#134]
Hi, we run benji for quite some time now and it becomes clear, that sqlite is no more the right approach.

Do we need to dump our backups now and start over or is there a way to migrate to postgresql?

Thanks

**Comment by elemental-lf** [comment]
You could import the metadata backups into a new database. But you'd have to enumerate the backups on the storage yourself and then import them one by one.

**Comment by elemental-lf** [comment]
I'm going to close this issue because there was no further feedback from the user.
