### ISSUE TITLE
Problems with snaptrims being pended - Work around

### ISSUE THREAD

**Issue by bbs2web** [elemental-lf/benji#137]
This is really intended to help others that may have problems when snaptrims get pended and subsequently don't get pruned. Symptom is that storage utilisation grows until OSDs are stopped and started. I presume us running Benji for many images overwhelms something somewhere and that Ceph subsequently stops trying to trim the snaps.

A graph of the available storage space shows continued utilisation until OSD processes were restarted this last weekend:
![image](https://user-images.githubusercontent.com/1456100/150334347-1dcae825-f2e5-498a-870b-5576ed8396f3.png)

The following can be used to remediate the problem by instructing Ceph to re-peer specific placement groups that have pending snaptrims. This avoids one having to restart services. In our case we simply added the following to the end of the daily Benji backup script:
```
# Force pending snaptrims to get processed:
for pg in `ceph pg ls -f json-pretty | jq -r '.pg_stats[] | select(.snaptrimq_len > 0) | .pgid'`; do
  ceph pg repeer $pg;
done
```

**Comment by elemental-lf** [comment]
Thank you for sharing. Are you seeing a [PG_SLOW_SNAP_TRIMMING](https://docs.ceph.com/en/latest/rados/operations/health-checks/#pg-slow-snap-trimming) health warning? According to the linked article the warning kicks in if `snaptrimq_len` exceeds `32768`. I just checked a Ceph cluster which is using Benji for backups and the largest `snaptrimq_len` in the `rbd` pool was `5118`. This is with Ceph 16.2.7.

**Comment by bbs2web** [comment]
Not at all, although it must be related to this as it only occurs when we run many snapshot purges as part of the Benjie backup process:
`[admin@kvm1b ~]# grep PG_SLOW_SNAP_TRIMMING /var/log/ceph/ceph.log`
`[admin@kvm1b ~]#`

**Comment by elemental-lf** [comment]
As this has been more of a PSA/FYI kind of thing I'm going to close this issue now. It can still be found via the search function of course.
