### ISSUE TITLE
Ceph RBD: Backups when object maps are invalid

### ISSUE THREAD

**Issue by olifre** [elemental-lf/benji#14]
This is more of a question than an issue (hopefully). What happens to a differential backup if the object-map is invalid?

I recently learned many of our snapshots have invalid object maps (Mimic, 13.2.1) for unclear reasons:
```
$ rbd --id=libvirt object-map check test-vm.example.com-disk2@b-2018-12-26T01:22:08+0100
Object Map Check: 5% complete...2019-01-09 17:42:06.709 7f8afcff9700 -1 librbd::ObjectMapIterateRequest: object map error: object rbd_data.88a47c83e458.0000000000000040 marked as 1, but should be 3
Object Map Check: 99% complete...2019-01-09 17:42:06.788 7f8af3fff700 -1 librbd::object_map::InvalidateRequest: 0x7f8ae00323e0 should_complete: r=0
Object Map Check: 100% complete...done
```
After a check, it's marked as invalid, and the same is then true for the fastdiff (could be recreated with `object-map rebuild`). 

So this question is two-fold:
- Does Benji explicitly check object maps? 
- Does Benji treat object maps marked as invalid correctly? 

Or is this all the user's responsibility, since the user runs `rbd diff` to feed the RBD hints to Benji?

**Comment by olifre** [comment]
Nota Bene: Other users have reported problems with object-map validity on the ceph-users mailing list recently:
http://lists.ceph.com/pipermail/ceph-users-ceph.com/2019-January/032092.html
So potentially, this issue is wide-spread.

**Comment by olifre** [comment]
Effects seem to be harmless, more details on my studies here:
http://lists.ceph.com/pipermail/ceph-users-ceph.com/2019-January/032223.html

The difference between state `1` and `3` seems to be `OBJECT_EXISTS` vs. `OBJECT_EXISTS_CLEAN`, so to my understanding, Benji / Backy2 only look at too many objects, but since the backend is deduplicated, this is not harmful. 

It still should be a bug somewhere in Ceph-RBD. Even though it is not your bug, it might be good to advice users of Benji / Backy2 to check their object-maps regularly when backing up using rbd diff hints just to be more safe, and maybe check validitiy in the provided example script before calling `rbd diff` if fast-diff is on.

**Comment by elemental-lf** [comment]
As you've already noted there is no logic in Benji to check this. Benji just works with the supplied hints. I'll mark this as a documentation enhancement as according to your research (thanks!) data integrity isn't compromised.
