### ISSUE TITLE
IO scheme k3s is undefined

### ISSUE THREAD

**Issue by achurak** [elemental-lf/benji#142]
Benji stopped working for me since 0.16. At first it was the issue that was fixed in 0.16.1 but unfortunately 0.16.1 just shows a different error now:

RuntimeError: benji invocation failed with return code 78 and output: {"event": "ConfigurationError: IO scheme k3s is undefined.", "level": "error", "timestamp": 1654373879.7829943, "file": "/benji/lib64/python3.6/site-packages/benji/scripts/benji.py", "line": 373, "function": "main", "process": 91, "thread_name": "MainThread", "thread_id": 139631292795776} 

It worked before 0.16 just fine with k3s so I assume the problem is not compatibility with k3s but rather some sanity check inside a script is not aware of this IO scheme.

Is there any way to make this work again? Thanks!

**Comment by elemental-lf** [comment]
Try defining an config of the RBD io module with the name `k3s` in your `benji.conf` or rename the `rbd` instance. The scripts search for a config named after the Ceph pool name. This is just a convention of the scripts.

**Comment by achurak** [comment]
Thanks so much! Looks like my values file for helm got messed up at some point without me noticing and the io module was pointing to file, not even rbd. I'm assuming I copy pasted some example accidentally.
