### ISSUE TITLE
Python 3.10 suport

### ISSUE THREAD

**Issue by Belgarion** [elemental-lf/benji#153]
I noticed some errors when installing benji on systems with python 3.10, but got it working with small changes.

sparsebitfield has 0.2.3 as latest version on pypi, which is broken in python 3.10, but you already have a fixed 0.2.4 in the git repo ( https://github.com/elemental-lf/sparsebitfield ) that has not been released to pypi.

ruamel.yaml, the current requirements in setup.py list >0.15,<0.16, but the oldest version that can be installed with python 3.10 is 0.16.0.
I tried changing the requirement to >0.15,<0.18 locally in setup.py and then installed with `pip install .[compression,s3,readcache]`

With those changes it so far seems to work fine with python 3.10 (backup is currently running).

**Comment by elemental-lf** [comment]
Thanks for the hints, @Belgarion, that was helpful. Current `master` should now be compatible with Python `3.10` and `3.11.`.
