### ISSUE TITLE
Document faster way to restore sparse backups to existing volumes

### ISSUE THREAD

**Issue by olifre** [elemental-lf/benji#16]
The following trick seems to work. 
I am unsure if it has an impact on shareability of objects in case there are clones of the volume, though (we don't use clones yet). 

```
# Check sizes... 
rbd info test-vm.example.com-disk1
rbd info test-vm.example.com-disk2
# Resize to "empty". Truncation resets all blocks to zero.
rbd resize --size 0M test-vm.example.com-disk1 --allow-shrink
rbd resize --size 0M test-vm.example.com-disk2 --allow-shrink
# Size back up.
rbd resize --size 20G test-vm.example.com-disk1
rbd resize --size 5G test-vm.example.com-disk2
benji restore -s -f 134 rbd://rbd/test-vm.physik.uni-bonn.de-disk1
benji restore -s -f 158 rbd://rbd/test-vm.physik.uni-bonn.de-disk2
```

The advantage over purging the volume and recreating it is that existing snapshots can be kept. 
Since Ceph RBD actively knows that all non-restored blocks are zeroed, it will also not consume space for them. 
Using restore without `-s` appears to consume full space (at least according to `rbd du`) until `fstrim` is used again after. 

If you do not find a flaw in my argumentation, it might be worthwhile to document it, or maybe even implement it as a flag in `benji restore` ;-).

**Comment by elemental-lf** [comment]
Yes, without `-s` it will actually write zeros. I'll mark this as a feature request and postpone it for the time being to concentrate on the bugs.

**Comment by olifre** [comment]
Fully agree with deprioritizing this :wink: . 
Potentially there's also a way to issue `DISCARD` for the full RBD volume which would be an even better trick.

**Comment by elemental-lf** [comment]
> Potentially there's also a way to issue `DISCARD` for the full RBD volume which would be an even better trick.

No, I don't think so as this would require Ceph to have knowledge about the filesystem structure.

**Comment by olifre** [comment]
>  this would require Ceph to have knowledge about the filesystem structure.

Are you sure? I would expect that `DISCARD` can be issued on block level, e.g. most `mkfs` commands first `DISCARD` /t rim the full device before putting anything on it to ensure an SSD knows that all data has / should have been wiped. 
My naïve expectation would be that this can be done without any filesystem knowledge if the full device is discarded (which would be fine if restoring to an existing volume).

**Comment by elemental-lf** [comment]
Yes, on second thought you're right. Benji could explicitly issue DISCARDs (or the Ceph equivalent) for the blocks it knows are sparse.

**Comment by elemental-lf** [comment]
Could you please try the changes in https://github.com/elemental-lf/benji/commit/e418c21f4ead829f04902fced2c29dbe7c1a3da8? Flags `-s` and `-f` need to be set as before.

**Comment by olifre** [comment]
Thanks for the implementation! Good to see that should work :+1: 
Sadly, I get:
```
benji --log-level DEBUG restore -s -f 161 rbd://rbd/test-vm.example.com-disk2
Traceback (most recent call last):
  File "/opt/benji/lib64/python3.6/site-packages/benji/scripts/benji.py", line 839, in main
    func(**func_args)
  File "/opt/benji/lib64/python3.6/site-packages/benji/scripts/benji.py", line 95, in restore
    benji_obj.restore(version_uid_obj, destination, sparse, force)
  File "/opt/benji/lib64/python3.6/site-packages/benji/benji.py", line 494, in restore
    io.open_w(version.size, force=force, sparse=sparse)
  File "/opt/benji/lib64/python3.6/site-packages/benji/io/rbd.py", line 99, in open_w
    self._writer.discard(0, image_size)
  File "rbd.pyx", line 2714, in rbd.Image.discard
rbd.InvalidArgument: [errno 22] error discarding region 0~5368709120
   ERROR: [errno 22] error discarding region 0~5368709120
```
The volume size seems to be correct, though:
```
# rbd --id=libvirt info test-vm.example.com-disk2
rbd image 'test-vm.example.com-disk2':
        size 5 GiB in 1280 objects
        order 22 (4 MiB objects)
```

**Comment by elemental-lf** [comment]
Thank you for testing. 22 is invalid argument. I'll take a look at the implementation in `librbd`.

**Comment by elemental-lf** [comment]
https://github.com/ceph/ceph/blob/7b111bd52459bc39036fe56047a8364f43a78796/src/librbd/librbd.cc#L2169
```c++
  int Image::discard(uint64_t ofs, uint64_t len)
  {
    ImageCtx *ictx = (ImageCtx *)ctx;
    tracepoint(librbd, discard_enter, ictx, ictx->name.c_str(), ictx->snap_name.c_str(), ictx->read_only, ofs, len);
    if (len > std::numeric_limits<int32_t>::max()) {
        tracepoint(librbd, discard_exit, -EINVAL);
        return -EINVAL;
    }
    int r = ictx->io_work_queue->discard(ofs, len, ictx->skip_partial_discard);
    tracepoint(librbd, discard_exit, r);
    return r;
  }
```
I've just pushed https://github.com/elemental-lf/benji/commit/6b6e79a33e3d7c1b2c6a2d26c986647b65e1ce2b which limits discard requests to 2^31-1. Could you try again please?

**Comment by olifre** [comment]
> Could you try again please?

Now it works perfectly well! I can also see the space allocation dropping to zero in `rbd du` and slowly increasing again during the restore. For sparse volumes, that's a heavy performance increase :+1: . 

Just a small final wish: It would be nice to also see the `DISCARD` mentioned in `--log-level DEBUG` just to make it visible that the code was executed. I guess it never really needs to enter the process name, since discards on Ceph RBD are "immediate" and then performed deferred in the background, so they never should take any time.

**Comment by elemental-lf** [comment]
I've added a message with level DEBUG to indicate that a discard operation will be initiated.
I think this wraps this issue up, I'm going to close it.

**Comment by olifre** [comment]
Thanks again! I hope this way to gain performance will be helpful to many users. For us, this reduces restore time by several factors :smile:.

**Comment by olifre** [comment]
Should the documentation be adapted to mention that using `-s` should be safe in general to existing volumes since `DISCARD` is issued first?
