### ISSUE TITLE
Slow incremental backup of empty, but large RBD volume

### ISSUE THREAD

**Issue by olifre** [elemental-lf/benji#17]
I have an RBD volume with 250 GB in size, zero blocks provisioned, daily snapshotted. 
The `rbd diff` between two snapshots is zero blocks. 
Taking a backup using this empty diff between two snapshots takes a large amount of time and is CPU bound (>1 hour on a slow machine). Benji is working at this stage:
```
benji [Preparing version V0000000314 (6.2%)]
```
Checking with `strace`, I see a lot of accesses to the `sqlite` backend (but not enough to explain the high CPU load alone). I presume the time is spent in the loop over all blocks:
https://github.com/elemental-lf/benji/blob/6b6e79a33e3d7c1b2c6a2d26c986647b65e1ce2b/src/benji/benji.py#L123

What's not yet clear to me:
- This time seems to be spent even though all blocks are sparse, and zero blocks have changed. Is this only the case since there is no non-empty backup?
- Do you have an idea what eats the time here? 

I'm thinking about hourly backups for some VMs with large volumes, but not-so-large changeset between the backups. If that slowness only affects RBD volumes which have always been empty, that's not a "real" issue, but if that's a constant overhead by total block count, it prevents that usecase. 

I don't observe this effect with Backy2, but a lot has changed in terms of metadata (and backy2 is slower in almost all other operations :wink: ).

**Comment by olifre** [comment]
PS: I'll rerun with `--log-level DEBUG` once the backup went through and report whether this highlights anything. I see there is debug output for example for the commit time to the metadata storage.

**Comment by olifre** [comment]
Ahhh! I found the cause. That explains why I did not see it the day before yesterday, but only now... 
```
self._COMMIT_EVERY_N_BLOCKS = 10
```
That was the sqlite bandaid here:
https://github.com/elemental-lf/benji/commit/3d95bfc621686e8908be11d07fa255493b392dca

Since each "commit" takes about a second here, for a volume with 250 GB and 4 MB blocksize = 64000 blocks it takes 6400 seconds alone to do the metadata commits to the SQLite DB even if nothing has changed at all. 
I believe that even for SQLite (which has a huge commit overhead) using `1000` seems like a much better choice, and increasing the timeout is a sufficient bandaid. What do you think?

**Comment by elemental-lf** [comment]
And now imagine that these one thousand blocks aren't empty and need to be written to AWS S3. This could take a considerable amount of time and the whole database will be locked. I can revert this change if you want but the SQLite based database will show problems the moment there are parallel writes. For example two `benji backup` processes running at the same time. PostgreSQL is really the way to go.

**Comment by olifre** [comment]
> And now imagine that these one thousand blocks aren't empty and need to be written to AWS S3. This could take a considerable amount of time and the whole database will be locked.

Yes, this would be a case when the locking is an issue. 



> I can revert this change if you want but the SQLite based database will show problems the moment there are parallel writes.

I think reverting it (but keeping the timeout) would be best. My reasoning would be that "small users" are likely to use local storage and SQLite, and not being able to perform operations in parallel is less of a loss for them than increasing the execution time by orders of magnitude, especially in such small setups. 
"Larger" users may employ a real DBMS such as PostgreSQL and get rid of those issues. I agree that this would be the best way to go in general. 

By the way, our reasoning for not using PostgreSQL yet is two fold: We want to have the backup system separated from the rest, without additional dependencies and need for additional services. 
We may reconsider that later on once we have a highly available, separately backed-up PostgreSQL cluster.

**Comment by elemental-lf** [comment]
>     * This time seems to be spent even though all blocks are sparse, and zero blocks have changed. Is this only the case since there is no non-empty backup?
Do you get the hints are empty warning?

This is the whole loop:
```python
            for i, block in enumerate(blocks):
                if block.id in read_blocks or not block.valid:
                    io.read(block)  # adds a read job.
                    read_jobs += 1
                elif block.id in sparse_blocks:
                    # This "elif" is very important. Because if the block is in read_blocks
                    # AND sparse_blocks, it *must* be read.
                    self._database_backend.set_block(
                        id=block.id,
                        version_uid=version.uid,
                        block_uid=None,
                        checksum=None,
                        size=block.size,
                        valid=True)
                    stats['bytes_sparse'] += block.size
                    logger.debug('Skipping block (sparse) {}'.format(block.id))
                else:
                    # Block is already in database, no need to update it
                    logger.debug('Keeping block {}'.format(block.id))
                notify(
                    self._process_name, 'Backing up version {} from {}: Queueing blocks to read ({:.1f}%)'.format(
                        version.uid.v_string, source, (i + 1) / len(blocks) * 100))
```
So the `set_block` is executed regardless of whether the block was already sparse or not. I think it would be okay to do this:

```python
[...]
                elif block.id in sparse_blocks:
                    # This "elif" is very important. Because if the block is in read_blocks
                    # AND sparse_blocks, it *must* be read.
                   if not block.uid:
                      self._database_backend.set_block(
                          id=block.id,
                          version_uid=version.uid,
                          block_uid=None,
                          checksum=None,
                          size=block.size,
                          valid=True)
                    stats['bytes_sparse'] += block.size
                    logger.debug('Skipping block (sparse) {}'.format(block.id))
[...]
```
I'd probably make this `if not block.uid and block.valid` because `_prepare_version` just copies the validity status of the old block. But there currently is no case where the block is sparse and not valid at the same time. (I think I actually already noticed this some time ago but feared that this optimisation would break something. Now I think that this fear was not warranted.)

There still is the loop in `_prepare_version` which copies blocks of the base version. This is always necessary.

**Comment by olifre** [comment]
> Do you get the hints are empty warning?

Yes, I do. 



> I'd probably make this `if not block.uid and block.valid` because `_prepare_version` just copies the validity status of the old block. But there currently is no case where the block is sparse and not valid at the same time. (I think I actually already noticed this some time ago but feared that this optimisation would break something. Now I think that this fear was not warranted.)

That looks like a good improvement. I can also not think of any way this would introduce breakage. 



> There still is the loop in `_prepare_version` which copies blocks of the base version. This is always necessary.

I believe this was the main part of the time I saw, spent in committing to the SQLite-DB. 
So another idea could be to not use `_COMMIT_EVERY_N_BLOCKS` but base that decision on the number of seconds since the last commit. This would scale automatically and allow for many blocks per commit in `_prepare_version` even when SQLite is used, but less commits when the actual backup is performed. At least for the `_prepare_version` part, the 10-block-commit interval is too excessive as it is IMHO.

**Comment by olifre** [comment]
I've beein thinking about the possibilities for a while now and here is what I have:

- Leave things as they are. 
  - :+1: Higher probability for parallel access to work with SQLite. 
  - :-1: Especially hits users with SQLite and disk-based backups ("small" users). Time for `_prepare_version` (constant overhead) increases for an empty 250 GB backup from less than 2 minutes to over 2 hours, plus the actual backup itself. 
  - :-1: Hits disks really hard, since SQLite flushes a significant amount of data to disk synchronously on each commit. 
- Roll back.
  - :+1: Fixes the slowness. 
  - :-1: Hits other users, especially in the actual write phase when the time spent with each block may be significantly larger. "Only" hinders concurrency, but does not drastically impact performance. 
- Use different `_COMMIT_EVERY_N_BLOCKS` for `_prepare_version` and actual block backup. 
  - :+1: Fixes the slowness without hitting other users too much. 
  - :-1: Uglifies the code, more hardcoded numbers, even worse if done DBMS dependent. 
- Use a _request_ mechanism, i.e. if benji instance **2** starts, it checks if there is a database lock, and if there is, it places a file in the data store which **1** notices and commits at the next possible chance. 
  - :+1: Commits are only done more frequently if really needed for parallelism. 
  - :-1: Uglifies the code.
  - :-1: Checking for existence of the file too often may take extra performance, hit network filesystems etc.
  - :-1: Locking may not cleanly work if a network filesystem is involved or more than one instance is waiting for the lock. 
  - :-1: You get all the mess of lockfiles for free (somehow getting rid of them if an instance suddenly crashed for example). 
- Use a time-based approach, i.e. commit "at least every x secs". Alternatively, may scale that with the time a commit actually takes. 
  - :+1: Automatically treats `_prepare_version` and actual block backup differently. 
  - :+1: Adapts to slow and fast backup I/O. 
  - :+1: Matches what filesystems are doing (mount-option `commit`). 
  - :+1: The timeout is also in seconds. So if the maximum commit interval is smaller than the timeout, for example, 10 seconds, it's almost guaranteed the timeout is never reached (unless a single block takes very long to back up, but then you have lost anyways with concurrency). 
  - :-1: `database.py` needs to track the time of the last commit. But you could get rid of `_COMMIT_EVERY_N_BLOCKS` :wink:. 

I believe I would personally favour the last option - at least no flaw has come to mind yet :wink:. 

What do you think?

**Comment by elemental-lf** [comment]
Option five sounds like a good idea and can't do much harm either way. I'd still go with a source code constant and not make this user configurable. (As far as a quick google could reveal there is no maximum transaction size in either PostgreSQL or SQLite, so we should be safe at that front.)
Thanks for listing the pro and cons. Again very helpful!

**Comment by olifre** [comment]
> I'd still go with a source code constant and not make this user configurable

I fully agree! 
Anything equal to / larger than 10 seconds is hopefully a good midway. SQLite should usually not take longer than 1-2 seconds for a commit, so in the worst case, SQLite users will spent 10-20 % CPU power and time committing in that case, but gain parallelism. 
Alternatively, something like "at minimum wait for 5 times the time a commit takes, but at maximum 30 seconds" might be fine. But I'll leave this to you :wink: 

EDIT: On second thought, the upper limit should probably be something like half the timeout.

**Comment by elemental-lf** [comment]
Just pushed https://github.com/elemental-lf/benji/commit/ebe877bb082f40b233b578b96f6c82cdef1dbc96. Please give it a try. I'm still pondering the other optimization.

**Comment by olifre** [comment]
Tested it just now, works very well!
My example (250 GB, empty RBD, SQLite as metadata backend) now uses only about 2 minutes again in `_prepare_version` instead of over two hours. Thanks!

**Comment by elemental-lf** [comment]
* I've added the optimization to skip `set_block` when the block was sparse to begin with. See https://github.com/elemental-lf/benji/commit/cf81fc4107af45f13ce0d4c11ff7bf8eccd2a77c. On second thought this won't speed up your use case I think. But maybe it'll help in other scenarios. 
* And to make things a little cleaner the SQLite timeout is now scaled in relation to the blocks commit interval. See https://github.com/elemental-lf/benji/commit/00b5e9b5a8b85bad1093f1ec597f5b611e940731.

I'll close this issue.
