### ISSUE TITLE
metadata-export and metadata-restore unavailable

### ISSUE THREAD

**Issue by damiandabrowski5** [elemental-lf/benji#18]
Hello,

I'm using latest version of elementalnet/benji docker container and I can't use metadata-export and metadata-restore commands.

> root@880e3487f43a:/# benji metadata-export
usage: benji [-h] [-v] [-m] [-V] [-c CONFIGFILE] [--no-color]
             {initdb,backup,restore,protect,unprotect,rm,enforce,scrub,deep-scrub,bulk-scrub,bulk-deep-scrub,export,import,export-to-backend,import-from-backend,cleanup,ls,stats,diff-meta,nbd,add-tag,rm-tag}
             ...
benji: error: invalid choice: 'metadata-export' (choose from 'initdb', 'backup', 'restore', 'protect', 'unprotect', 'rm', 'enforce', 'scrub', 'deep-scrub', 'bulk-scrub', 'bulk-deep-scrub', 'export', 'import', 'export-to-backend', 'import-from-backend', 'cleanup', 'ls', 'stats', 'diff-meta', 'nbd', 'add-tag', 'rm-tag')
root@880e3487f43a:/# benji metadata-restore
usage: benji [-h] [-v] [-m] [-V] [-c CONFIGFILE] [--no-color]
             {initdb,backup,restore,protect,unprotect,rm,enforce,scrub,deep-scrub,bulk-scrub,bulk-deep-scrub,export,import,export-to-backend,import-from-backend,cleanup,ls,stats,diff-meta,nbd,add-tag,rm-tag}
             ...
benji: error: invalid choice: 'metadata-restore' (choose from 'initdb', 'backup', 'restore', 'protect', 'unprotect', 'rm', 'enforce', 'scrub', 'deep-scrub', 'bulk-scrub', 'bulk-deep-scrub', 'export', 'import', 'export-to-backend', 'import-from-backend', 'cleanup', 'ls', 'stats', 'diff-meta', 'nbd', 'add-tag', 'rm-tag')

**Comment by elemental-lf** [comment]
Hi there!
Are you sure that you're using the latest image? I'm asking because it works for me:
```
[lf@gimli ~]$ docker pull elementalnet/benji
Using default tag: latest
latest: Pulling from elementalnet/benji
a02a4930cb5d: Pull complete 
d1086c129307: Pull complete 
1776c34527be: Pull complete 
c215798e68c2: Pull complete 
94cbfcdd8454: Pull complete 
b05de2194fd4: Pull complete 
804ae0d8412c: Pull complete 
a8e8a378e510: Pull complete 
95bb06e82690: Pull complete 
Digest: sha256:0511696f87e6b5fe5572077ce296ed4a8941da409b82892ac242ebcc08457b86
Status: Downloaded newer image for elementalnet/benji:latest
[lf@gimli ~]$ docker run -it elementalnet/benji
bash-4.2# benji 
usage: benji [-h] [-c CONFIG_FILE] [-m]
             [--log-level {DEBUG,INFO,WARNING,ERROR}] [--no-color]
             {backup,restore,nbd,label,ls,rm,enforce,cleanup,protect,unprotect,scrub,deep-scrub,batch-scrub,batch-deep-scrub,metadata-export,metadata-import,netadata-backup,metadata-restore,metadata-ls,stats,version-info,init,migrate}
             ...

```
And I've checked: Even the image that was built 19 days ago contains this CLI name change already. So could you please try again after a `docker pull elementalnet/benji`?

**Comment by damiandabrowski5** [comment]
Hi,

You're right, I wasn't using latest image, after upgrade works fine(unfortunately, new problem occured bit I'll create seperate issue for it)

**Comment by elemental-lf** [comment]
Thanks for the feedback! I'll close this issue.
