### ISSUE TITLE
Dumb question - How do we use the scripts?

### ISSUE THREAD

**Issue by CoryHawkless** [elemental-lf/benji#19]
How do we leverage the scripts provided at benji/scripts/ceph.sh etc?
Running bash ceph.sh fails with 
```
bash-4.2# source scripts/ceph.sh
bash: scripts/ceph.sh: line 64: syntax error near unexpected token `}'
bash: scripts/ceph.sh: line 64: `        } catch {'
bash-4.2#
```
I'm sure i'm missing something here? I'd rather not have to rewrite the script into 'standard' bash or use the old Backy2 scripts, this one looks to do exactly what I want, I just cant figure out how to use it :/

**Comment by elemental-lf** [comment]
I'm sorry this is still mostly undocumented. Please have a look at https://github.com/elemental-lf/benji/blob/master/images/benji-k8s/scripts/benji-pvc-backup. You need to include the scripts in this order:
```bash
. prometheus.sh
. metrics.sh
. tryCatch.sh
. common.sh
. ceph.sh
```
Then you can start a backup by using `benji::backup::ceph`:
```bash
        benji::backup::ceph "$NAME" "$CEPH_POOL" "$CEPH_IMAGE" \
            "benji-backup.me/instance=$BENJI_INSTANCE" \
            "benji-backup.me/ceph-pool=$CEPH_POOL" \
            "benji-backup.me/ceph-image=$CEPH_IMAGE" \
            "benji-backup.me/k8s-pvc-namespace=$PVC_NAMESPACE" \
            "benji-backup.me/k8s-pvc-name=$PVC_NAME" \
            "benji-backup.me/k8s-pv=$pv"
```
This is mostly self-explaining. The last few arguments are all labels and are optional. The Prometheus stuff needs to be included but if you don't explicitly export the metrics, then nothing happens with them. Other commands can be called with the `benji::command` wrapper but you don't need to, it only captures the Prometheus metrics currently. If you have further questions, please just ask.

**Comment by CoryHawkless** [comment]
Ok, that helps alot.
Based on that info, here is a script I came up with

```
#!/usr/bin/env bash

echo "Running for $1 $2 $3"

NAME="$1"
CEPH_POOL="$2"
CEPH_IMAGE="$3"

. /benji/scripts/prometheus.sh
. /benji/scripts/metrics.sh
. /benji/scripts/tryCatch.sh
. /benji/scripts/common.sh
. /benji/scripts/ceph.sh


benji::backup::ceph "$NAME" "$CEPH_POOL" "$CEPH_IMAGE" "AutomatedBackup"

```

I can then run a backup using something like this

`backupScript.sh BackupName PoolName volume-name`

And because I'm using docker, I can just run a fresh container with all the files mapped like so

`docker run --interactive --tty -v "$PWD/benji.yaml:/etc/benji/benji.yaml" -v"$PWD/benji.sqlite:/tmp/benji.sqlite" -v"$PWD/ceph.conf:/etc/ceph/ceph.conf" -v"$PWD/ceph.client.admin.keyring:/etc/ceph/ceph.client.admin.keyring" -v"$PWD/backupScript.sh:/benji/scripts/backupScript.sh"  --rm elementalnet/benji /benji/scripts/backupScript.sh BackupName PoolName volume-name`

**Comment by elemental-lf** [comment]
Thanks for your feedback. I'm glad that you're up and running, I'll close this issue.
