### ISSUE TITLE
Cleanup is terribly slow

### ISSUE THREAD

**Issue by damiandabrowski5** [elemental-lf/benji#23]
Hello,

I'm using benji with rbd and backblaze and I've made simple test:

1. Backed up two 25GB rbd volumes - took 45 minutes
2. Executed benji cleanup to remove unused block from backblaze - took 110 minutes

Summary: removing backups takes 2,5x more time than doing backups.

Is there any chance to speed up this process?

**Comment by elemental-lf** [comment]
> Is there any chance to speed up this process?

Probably ;) The cleanup process is not parallelized at all at the moment so it's probably the time spent talking to the B2 API which slows things down. But I'd need a log at level DEBUG with timestamps to confirm this. Unfortunately the logfile written by Benji is always at level INFO. I'll need to fix this before you'd be able to provide the needed information. I'll update this issue when it's done.
These things aside the cleanup process isn't timing critical at all and it can run in parallel to all other operations apart from itself.

**Comment by elemental-lf** [comment]
The latest master branch should be able to log to a logfile (`logFile` directive in `benji.yaml`) at DEBUG level. If you're using the Docker images then you should be able to get this change by repulling the image with the `latest` tag. Could you then please configure a logfile, start `benji cleanup` with `--log-level DEBUG` and provide the resulting logfile to me? Depending on how many delete candidates there are the logfile might be quite big. It should suffice if you post the first hundred lines or so. Thank you!

**Comment by elemental-lf** [comment]
I think it is also extra slow because  B2 has no bulk delete operation. I'm currently working on concurrent deletes similar to the model used by storage reads and writes. And while I'm at it I will also implement several parallel writer threads during restore as well.

**Comment by elemental-lf** [comment]
@Scooty5 I just released 0.3.0 which includes the multi-threaded removal of blocks. Could you give it a try please?

**Comment by elemental-lf** [comment]
Better try current master ;)

**Comment by damiandabrowski5** [comment]
sorry for long reply :/

now is much faster, thank You!

deleting 18GB took 11min
