### ISSUE TITLE
Large RBD Volume backups are very slow

### ISSUE THREAD

**Issue by adambmedent** [elemental-lf/benji#29]
Hey guys I have been testing quite a bit with Benji.  I am using Benji with a simple Postgressql database.  

I am noticing that it takes a very long time to backup a large RBD volume with no changes.  

For example I have two RBD volumes setup.  1 is 6TB and 1 is 500G.  The 500G volume with no change takes 4 minutes for a complete backup.  The 6TB volume takes between 80-100 minutes.    

Is there anything which can be done to speedup this process?  It seems the benji preparation step is limited to a single CPU and just spins at 100%.  

As a comparison, backy2 is able to backup this same volume in 20 minutes.  Which is still pretty long for no change.

**Comment by elemental-lf** [comment]
Hmm, by preparation step you mean that the process name is something like `Preparing version` and an increasing percentage? And this takes most of the time? If that is the case then this needs to be optimized by making the database inserts more efficient and probably by bypassing parts of SQLAlchemy.
But for a 6TB volume both backy2 and benji need to insert 1.5 million rows into the blocks table when using a block size of 4MB. This will take some time in any case. When most of these blocks are sparse then this could be optimized significantly I think. I will need to think about the implications. If the volume consists of mostly used blocks then there might be some optimization potential by chaining versions. But at first glance this would make things complex, introduce race conditions and would make version removals a lot slower so there might be no win at all. Do you know if your 6TB volume is mostly sparse?

**Comment by elemental-lf** [comment]
@adambmedent, could you please try branch `create_blocks` and see if it makes a difference? It uses a special bulk insert feature of SQLAlchemy which should reduce the overhead of preparing a version significantly.
You can directly install a branch with `pip`: `pip install git+https://github.com/elemental-lf/benji@create_blocks`

**Comment by elemental-lf** [comment]
@adambmedent I'd like to add some other optimizations, so please wait with the test. Thanks.

**Comment by adambmedent** [comment]
> @adambmedent I'd like to add some other optimizations, so please wait with the test. Thanks.

Sounds good, I am ready when you are.

**Comment by elemental-lf** [comment]
I think you can give it a try, now. I tried to address memory usage, too. So hopefully it will also use less memory for versions with many blocks. There still is one place where a large data structure is built though.

**Comment by adambmedent** [comment]
So far in testing this change has proven to be very beneficial.

Before the change a 6TB sparse volume would take roughly 90 minutes to do a incremental backup with no changes.  After the change it is now taking roughly 15 minutes.  

Nice improvements!

**Comment by elemental-lf** [comment]
Could you please do a deep-scrub on the new version(s)? I just want to get some more reassurances that I didn't break anything as the changes are not trivial.

**Comment by adambmedent** [comment]
Looking solid.

    INFO: Set status of version V0000000061 to valid.
    INFO: Deep-scrub of version V0000000061 successful.

I will  be beating on this setup consistently to work out any kinks.

**Comment by elemental-lf** [comment]
Sounds good, thank you. After I've done some further tests I'm going to  merge `create_blocks` into `master` soon.
