### ISSUE TITLE
state of project

### ISSUE THREAD

**Issue by jubalh** [elemental-lf/benji#3]
Hi,

I found this project after I discovered some problems with backy2.

I started packaging backy2 for openSUSE, but it is too unmaintained from upstream to make it into the distro. I wondered what are the plans about this fork. It seems much more active and well maintained.

However when writing an email to maintainer the mail bounced back. Not a good sign either :-)

I would like to know what your future goals with this project are and how reliable it will be.
Thanks.

**Comment by elemental-lf** [comment]
I'm sorry for the late reply, I've been busy with another project.  And I'm sorry for the bouncing email. I acknowledged an alarm from my email server by accident and then I didn't notice the problem in time.

Benji is still part of a project I'm working on for a customer and I'll revisit it later this year or at the beginning of next year. The goal is to provide a stable and reliable backup solution in this customer's environment in the near future (1Q2019). I'm also in contact with one academic user from Germany who is currently testing Benji in parallel to Backy2. Feedback has been positive up to now. Still I wouldn't consider Benji a stable piece of software at the moment. Too much has changed in relation to Backy2 and it needs a longer period of testing. Furthermore I'm planning at least one change of the database schema, but there'll probably be a migration path. I've just updated the TODO list to reflect my current priorities. Please see https://github.com/elemental-lf/benji/blob/master/TODO.rst.

**Comment by jubalh** [comment]
@elemental-lf thank you for your reply.

This sounds promising. Please notify me by commenting on this issue or writing me an email in case benji becomes stable. I have heard of other users using it happily, and if you plan to maintain it over a longer period of time I would volunteer to package it for openSUSE and maintain it there.

**Comment by elemental-lf** [comment]
I'll leave this issue open for now as documentation for the current of state of affairs.

**Comment by jubalh** [comment]
It seems that you delete the 0.0.0 [tag](https://github.com/elemental-lf/benji/releases) and recreate it upon new commits.

This can create problems:
In my [package](https://build.opensuse.org/package/view_file/home:jubalh/benji) I download the tarball 0.0.0 at a certain time, if you later do commits, remove the old tag, and reuse it on a different commmit my tarball will have the same version number but a totally different state.

**Comment by elemental-lf** [comment]
Superseding the tag was on purpose and will probably happen again as long as there are no official releases. AFAIK GitHub doesn't support ``git archive``  of an arbitrary commit, which would probably help here. I will add a note to the 0.0.0 tag explaining this.

**Comment by jubalh** [comment]
Yeah I asumed that it is on purpose. I just wanted to point out that this will make my current package pretty useless for testing and I was not aware that you do this until I saw the update tag. Yeah I think the note would be good. I will change the package later to build from git master instead from the tag. Then it can still be used for testing benji.

**Comment by elemental-lf** [comment]
@jubalh I started making releases which are also in PyPI but the master branch is still recommended. I'm going to close this issue as it contains outdated information now.

**Comment by jubalh** [comment]
@elemental-lf very nice to hear. I will update the benji package in my private repo tomorrow.
Is it also ready to go into the offical distribution, meaning do you plan to continue on it for a longer time?

One thing that would be nice would be a Changelog/News file.

**Comment by elemental-lf** [comment]
@jubalh sorry, again missed a closed issue with a new comment...
> Is it also ready to go into the offical distribution, meaning do you plan to continue on it for a longer time?

Yes, probably. But it will still take some time before everything stabilizes. 
With 0.2.0 I tried to document the main changes. I should probably put it into a file inside the repository, too.

**Comment by jubalh** [comment]
Awesome. Thanks for this!
