### ISSUE TITLE
Retention Policy and Epoch time stamps

### ISSUE THREAD

**Issue by adambmedent** [elemental-lf/benji#30]
Working with enforcing a retention policy and I am hitting a somewhat odd issues.  

Benji is reporting the epoch time stamp for the existing snapshots in the "future", which is causing the enforce option to not work as expected.  

| 2019-03-26T09:58:58 | V0000000018 | vm-101-disk-0 | 2019-03-26T09:58:20 |    2.0TiB |     4.0MiB | valid  |   False   | Ceph-Backup |

As you can see the date is 3-26-2019 at 09:58:58, but when I run benji enforce its not the same.  

[root@ceph-backups ~]# /usr/local/benji/bin/benji enforce hours3 --dry-run
    INFO: $ /usr/local/benji/bin/benji enforce hours3 --dry-run
 WARNING: Version V0000000018: 1553623138.596453 isn't earlier than the reference time 1553611165.268765.

1553623138.596453 = Tue, 26 Mar 2019 13:58:58 -0400

Is there an option I need to add to have benji properly calculate this epoch with my proper timezone?  Benji is reporting the correct current epoch.

**Comment by elemental-lf** [comment]
At first glance this looks like a bug. One of those very popular time handling bugs which everyone loves so much ;) I probably didn't see this because my local time is ahead of UTC and yours is behind. Will have to look into this...

**Comment by elemental-lf** [comment]
I just committed a fix in https://github.com/elemental-lf/benji/commit/7936629494a98dbd0a3e0da19b04ae05882f6253. Could you please test if you still get the warning with current master?

**Comment by adambmedent** [comment]
> I just committed a fix in [7936629](https://github.com/elemental-lf/benji/commit/7936629494a98dbd0a3e0da19b04ae05882f6253). Could you please test if you still get the warning with current master?

I will be testing shortly.  Appreciate the quick fix.

**Comment by adambmedent** [comment]
Testing is looking good, so far no issues.  I will report back if I hit anything.  We plan on using this enforcement feature pretty heavily.

**Comment by elemental-lf** [comment]
Thanks for reporting back. I'll close this issue.
PS: There is one undocumented feature for enforce which I haven't tested thoroughly yet. With the `-g` option you can specify a group label. If one version is identified for removal then all versions which have the same vale for this label are scheduled for removal, too. This might be useful for consistency groups or other groups of images.

**Comment by adambmedent** [comment]
Looks like there are still some issues with enforcement.  

[root@udarchive-benji ~]# /usr/local/benji/bin/benji enforce latest1,days525 --dry-run
    INFO: $ /usr/local/benji/bin/benji enforce latest1,days525 --dry-run
    INFO: Removing versions: vm-278-disk-0-rbm1dy, vm-280-disk-0-fue563.
    INFO: Dry run, won't remove anything.

[root@udarchive-benji ~]# /usr/local/benji/bin/benji ls | grep vm-278-disk-0-rbm1dy
    INFO: $ /usr/local/benji/bin/benji ls
| 2020-05-27T01:09:29 | vm-278-disk-0-rbm1dy | vm-278-disk-0 | benji-ccs-2020-05-27T01:09:26    |  100.0GiB |     4.0MiB |  valid  |   False   | benji-ccs    |                                      [root@udarchive-benji ~]# /usr/local/benji/bin/benji ls | grep vm-280-disk-0-fue563
    INFO: $ /usr/local/benji/bin/benji ls
| 2020-05-27T01:09:44 | vm-280-disk-0-fue563 | vm-280-disk-0 | benji-ccs-2020-05-27T01:09:41    |  100.0GiB |     4.0MiB |  valid  |   False   | benji-ccs    |

Both of these versions are from 5-27-20, not sure why benji is seeing them as 525 days old.  Any ideas?
