### ISSUE TITLE
Database migration fails with sqlite

### ISSUE THREAD

**Issue by olifre** [elemental-lf/benji#32]
Hi,

after adopting https://github.com/elemental-lf/benji/commit/cb2447c4709446ead3e8f789b20121d472c51703 , I get:
```
# benji database-migrate
    INFO: $ /opt/benji/bin/benji -c /etc/benji.yaml database-migrate
    INFO: Migrating from database schema revision fe79ce75cefa to 151248f94062.
   ERROR: NotImplementedError: This backend does not support multiple-table criteria within UPDATE
```

**Comment by olifre** [comment]
https://stackoverflow.com/questions/329197/cross-table-update-in-sqlite3 indicates that this can be emulated with subselects. But I'm not really acquainted with alembic, otherwise I'd have done a PR.

**Comment by elemental-lf** [comment]
Hmm but `INSERT AND REPLACE` doesn't fit our use case. So I've decided to not migrate the old statistics for SQLite. But I'll need to figure out how to skip something in Alembic based on dialect. Doesn't seem to be straight forward or I'm not seeing the forest for the tress. 
@olifre, you can just comment out the part where it fails and then the migration should run through. But you'll lose all statistics.

**Comment by olifre** [comment]
@elemental-lf Ah, sorry, I did not mean the `INSERT OR REPLACE` apprach :wink: . 
I was thinking about something like doing (plain SQL) right after the `ALTER`:
```
UPDATE versions SET bytes_dedup = (SELECT bytes_dedup FROM version_statistics WHERE versions.uid == version_statistics.uid);
UPDATE versions SET bytes_read = (SELECT bytes_read FROM version_statistics WHERE versions.uid == version_statistics.uid);
UPDATE versions SET bytes_sparse = (SELECT bytes_sparse FROM version_statistics WHERE versions.uid == version_statistics.uid);
UPDATE versions SET bytes_written = (SELECT bytes_written FROM version_statistics WHERE versions.uid == version_statistics.uid);
```
This should work in all SQL flavours, since it's not a cross-table update. 

But of course, it's also not a problem to just drop the stats, but to prevent others from encountering that problem, maybe this approach is the easier solution :wink:

**Comment by olifre** [comment]
@elemental-lf An alternative approach appears to be fetching all old values and injecting them - the advantage is that there's an example in alembic here: https://stackoverflow.com/a/43958757 
I'm fine either way, just let me know if you want to implement one of these ways, or rather document that stats are lost (btw.: I also did not find anything on how to find out which backend is in use :cry: ).

**Comment by elemental-lf** [comment]
I had seen the `UPDATE` with subselect approach but didn't think far enough. This is what I'm getting now and it looks okay but is untested:
```sql
UPDATE versions SET bytes_dedup=(SELECT version_statistics.bytes_dedup 
FROM version_statistics  WHERE versions.uid = version_statistics.uid), bytes_read=(SELECT version_statistics.bytes_read 
FROM version_statistics  WHERE versions.uid = version_statistics.uid), bytes_sparse=(SELECT version_statistics.bytes_sparse 
FROM version_statistics WHERE versions.uid = version_statistics.uid), bytes_written=(SELECT version_statistics.bytes_written 
FROM version_statistics  WHERE versions.uid = version_statistics.uid), duration=(SELECT version_statistics.duration 
FROM version_statistics  WHERE versions.uid = version_statistics.uid)
```
And I've noticed that `op.execute()` would accept the SQL expression as a simple string too...
Could you please try branch `stats-migration`? It contains the new migration code:
```python
    op.execute(versions.update().values({
        versions.c.bytes_dedup:
        sa.sql.select(columns=[version_statistics.c.bytes_dedup]).where(versions.c.uid == version_statistics.c.uid),
        versions.c.bytes_read:
        sa.sql.select(columns=[version_statistics.c.bytes_read]).where(versions.c.uid == version_statistics.c.uid),
        versions.c.bytes_sparse:
        sa.sql.select(columns=[version_statistics.c.bytes_sparse]).where(versions.c.uid == version_statistics.c.uid),
        versions.c.bytes_written:
        sa.sql.select(columns=[version_statistics.c.bytes_written]).where(versions.c.uid == version_statistics.c.uid),
        versions.c.duration:
        sa.sql.select(columns=[version_statistics.c.duration]).where(versions.c.uid == version_statistics.c.uid),
    }))
```

**Comment by olifre** [comment]
> And I've noticed that `op.execute()` would accept the SQL expression as a simple string too...

Ah! Yes, indeed then I could have tested myself. But it's probably more portable if another dialect ever comes up to use the sqlalchemy / alembic syntax. 



>  Could you please try branch `stats-migration`? It contains the new migration code:

It seems to work perfectly well! 
Of course, after trying with `master` before, the DB was "half-migrated", since the extra columns were already added to the `versions` table. But I recovered the SQLite-DB from a backup and then migrated with the branch code and now I have a `versions` table with statistics data. Also, `benji ls -s` looks good :wink:. 

Of course the new code may be more inefficient with a "real" DBMS (it's 5 subselects after all - but maybe PostgreSQL query planner can optimize that out anyways), but the `versions` table is never really large (we have about 7000 versions, and the migration took SQLite a second or so), so I believe that's not an issue, and it spares us all from trying to find a way to instruct the migration to skip a part depending on backend dialect. 

Many thanks again! 
I'll now be able to profit from the recent performance gains (for the prepare stage), let's see how much this helps in our setup.

**Comment by elemental-lf** [comment]
Thanks! And yes, it's inefficient, but for a one time migration with not too many records it doesn't pose a problem. (And we're still in a  pre-release state after all.)
The optimizations should help a lot for large backups. I also replaced two other complete table scan (one in the sanity check and one as part of a restore). But the metadata backup still needs a lot of memory for large volumes. I'm thinking about the best way to solve this.
