### ISSUE TITLE
question: structlog

### ISSUE THREAD

**Issue by jubalh** [elemental-lf/benji#35]
Hi, quick question:
Is structlog a must have for 0.5.0?

**Comment by elemental-lf** [comment]
Yes, it is. I'm planning to add JSON formatted logging in a future version and I would also like to augment existing logging messages with extra information. Mainly this will be the version uid but backup and snapshot name might also be useful. Things like process id, thread name, function name, file name and line number are already present as extra data elements.
Is there a problem with `structlog`? Did I miss something?

**Comment by jubalh** [comment]
Thanks for the answer!

`Is there a problem with structlog?`

Not at all (to my knowledge). So far it was just not packaged for openSUSE. I packaged it now and it waits to go into distribution repos. Once it's added benji 0.5.0 will follow.
