### ISSUE TITLE
Odd deduplication Results

### ISSUE THREAD

**Issue by adambmedent** [elemental-lf/benji#38]
I am in the process of testing Benji to backup to two separate storage locations.  

I currently have 15 RBD volumes, all of which have 43G of 100G used.  14 of them are benji restores from the original image.  

The first initial backup to the first storage resulted in 43G of data used.  

The first initial backup to the 2nd storage resulted in 114G of data used.  

Seeing as I am backing up the same block devices, shouldn't I get similar results in space utilization?  

I attempted to run a cleanup on the storage as well, but there wasn't anything to clean up.

**Comment by adambmedent** [comment]
Actually thinking this out more, I might have just answered my own question.  

When I did the initial backup to the first storage, I did a backup of the first block device only.  When I did the initial backup to the 2nd storage, I let the script handle it and had 5 benji backups running at the same time.  I am guessing I didn't get as good as dedup numbers because those 5 backups were running at the same time and not valid yet.  Once one them went valid benji was able to see existing blocks?

| 2019-04-11T00:11:53 | V0000000296, hints      | vm-106-disk-0 | set-b-2019-04-11T00:11:51 |  100.0GiB |     4.0MiB | set-b   |   32.0GiB |      0.0B |   32.0GiB |   0.0B |     03m 26s |
| 2019-04-11T00:11:39 | V0000000295, hints      | vm-105-disk-0 | set-b-2019-04-11T00:11:37 |  100.0GiB |     4.0MiB | set-b   |   32.0GiB |      0.0B |   32.0GiB |   0.0B |     03m 14s |
| 2019-04-11T00:05:05 | V0000000290, hints      | vm-100-disk-0 | set-b-2019-04-11T00:05:03 |  100.0GiB |     4.0MiB | set-b   |   41.7GiB |   23.2GiB |   18.5GiB |   0.0B |     06m 13s |
| 2019-04-11T00:05:52 | V0000000293, hints      | vm-103-disk-0 | set-b-2019-04-11T00:05:49 |  100.0GiB |     4.0MiB | set-b   |   32.0GiB |   19.3GiB |   12.7GiB |   0.0B |     05m 26s |
| 2019-04-11T00:05:36 | V0000000292, hints      | vm-102-disk-0 | set-b-2019-04-11T00:05:34 |  100.0GiB |     4.0MiB | set-b   |   32.0GiB |   24.2GiB |    7.7GiB |   0.0B |     05m 42s |
| 2019-04-11T00:05:21 | V0000000291, hints      | vm-101-disk-0 | set-b-2019-04-11T00:05:19 |  100.0GiB |     4.0MiB | set-b   |   32.0GiB |   31.5GiB |  448.0MiB |   0.0B |     05m 57s |
| 2019-04-11T00:06:06 | V0000000294, hints      | vm-104-disk-0 | set-b-2019-04-11T00:06:04 |  100.0GiB |     4.0MiB | set-b   |   32.0GiB |   14.7GiB |   17.2GiB |   0.0B |     05m 10s |

**Comment by elemental-lf** [comment]
Blocks are considered for deduplication as soon as they appear in the database. The version doesn't have to be complete and valid, yet.

EDIT: But there will be some delays due to database transaction handling.

**Comment by adambmedent** [comment]
Yea I am thinking I simply hit a delay in the database transaction handling.  It makes sense to me,  You can close this one out.
