### ISSUE TITLE
CEPH url error

### ISSUE THREAD

**Issue by devopstales** [elemental-lf/benji#39]
solved. can be close

**Comment by olifre** [comment]
If you get the error:
```
ERROR: UsageError: The supplied URL rbd://vm-live/vm-118@test is invalid.
```
I think the new syntax is:
```
rbd:vm-live/vm-118@test
```
for an RBD pool called `vm-live`. Since this did not make it into the provided sample scripts and all places of the documentation yet (I think), this issue should probably stay open until that is resolved.

**Comment by elemental-lf** [comment]
@devopstales thanks for bringing that to my attention. With the latest changes regarding iSCSI I switched from using regular expressions to using ``urllib.parse`` which is stricter about URL syntax than the regular expressions were. I need to update the documentation and scripts as I don't plan on going back to the old way of parsing. I'm sorry for the confusion.

**Comment by elemental-lf** [comment]
Documentation and messages are fixed now. See https://github.com/elemental-lf/benji/commit/89d2f37c73f3aa821ff4852d9cbfb03af72f00a2. Hopefully I didn't botch anything else. I'm currently busy with other things and I'm trying to multi-task here...

**Comment by gregzuro** [comment]
Seems like there are at least two occurrences of the (very?) old syntax in the docs: https://github.com/elemental-lf/benji/search?q=TESTFILE

**Comment by elemental-lf** [comment]
@gregzuro Thanks! I fixed it just now.
