### ISSUE TITLE
Anyway to improve restore speeds

### ISSUE THREAD

**Issue by adambmedent** [elemental-lf/benji#40]
I could be missing something but I was wondering if there is anyway to improve the restore of a benji backup.  

Ive messed with these settings and they don't seem to have much effect.

    simultaneousReads: 
    simultaneousWrites: 

The best I can ever get is about 15MB/s in writes during the restore.  Benji is setup on a host which has a 10G connection on the ceph public network.  I can mount up a rbd volume on the benji VM and write out at 200MB/s. 

Maybe there are some other settings to improve this?  Appreciate the input as always!

**Comment by elemental-lf** [comment]
@adambmedent I haven't done much benchmarking yet so thanks for tackling this topic. Have you also tuned the reader side? I mean increasing the simultaneous readers on the storage side? Furthermore you could try to enable the read cache on the storage side. But as far as I remember you're writing the backups to a file based storage anyway, so the read cache would only be useful when the file based storage is remote (and slower) and the cache is local (and faster).

**Comment by adambmedent** [comment]
Yea I have tried that as well.  

Going from the default of simultaneousReads: 1 and simultaneousWrites: 1 to 2 only provides about a 5% change.  Anything above 2 doesn't seem to make a difference at all other than more CPU usage.  

Yep backups are going to a file based storage and our restores will be extremely random.

Testing with a disk that is 100G in size, and has roughly 32G of data on it.  Takes about 40 minutes which isn't to bad, but I was hoping for a bit more as the process only seems to be writing at about 15-20MB/s to the ceph storage.

**Comment by elemental-lf** [comment]
I'll look into this. Maybe it's also time to add some statistics to the restore process so that the restore duration and speed are more obvious. (@adambmedent you are using the `-s`/`--sparse` flag for the restore? Otherwise sparse blocks would be actually written as consecutive zeros.)

**Comment by elemental-lf** [comment]
I have another suspicion: Benji as the original code in Backy2 opens and closes the RBD image for every read and write. This simplifies the code in the multi-threaded context that it is run in. But there certainly will be some overhead to this and I'm not sure if this is significant or not. But I always had the hunch that this mighty be problematic. Probably the RADOS client will contact the Ceph monitors on each open  and download the current cluster map and this can't be cheap. This shouldn't be too hard to fix by using multiple image handles, one for each thread. Could you run your restore with `--log-level=DEBUG`? I'm only interested in the lines generated by this code:
```python
        logger.debug('{} wrote block {} in {:.2f}s'.format(
            threading.current_thread().name,
            block.id,
            t2 - t1,
        ))
```
Hopefully the resolution of 0.01s is enough to see something...

**Comment by elemental-lf** [comment]
I've looked into this and creating librados I/O contexts shouldn't be that expensive. The expensive part is creating the cluster handle. I haven't looked into the RBD part yet. But apart from that I'm not sure if we get any benefit from Python threads at all in the way the code is currently written.

**Comment by adambmedent** [comment]
I attached a restore log with debugging enabled.  

I have tested with both sparse and without sparse and I didn't see much a difference, but 90% of my testing has been with the sparse option.  

[benji_restore.log](https://github.com/elemental-lf/benji/files/3216692/benji_restore.log)

Ive reviewed my setup as well and I don't think im hitting any major performance limits.

Let me know if I can provide anything else.

**Comment by adambmedent** [comment]
For fun I decided to test restoring to a file instead of a rbd device and the results were much different.

File restore took about 2 minutes, vs 40 minutes for a restore to rbd.  The file restore was writing at a steady 400MB/s vs 15MB/s for rbd.  

I don't think my ceph cluster is the bottle neck as I can do a rbd clone and easily hit 70-100MB/s on that directly from my benji VM.  

Im glad to see this as we can easily restore to file for access to the data if its needed.   Would be cool to get the rbd restore working just as good.

Did I mention benji is awsome!

**Comment by elemental-lf** [comment]
I took a look at the `librbd` code and I think that the RBD image open is expensive and so should only be done once per thread. I have some work in progress in https://github.com/elemental-lf/benji/tree/rbd-thread-local. But I've just written the code and didn't do any testing at all yet. Even if this works out, an implementation using the asynchronous I/O functions of `librbd` might be worth it. In this case only one RBD context would be needed and there wouldn't be any threads at all which should save some resources and make things more efficient.

**Comment by elemental-lf** [comment]
@adambmedent just a small update: I'm still working on this in the background alas with reduced speed. I've decided to leave the current code alone and try to implement something based on the AIO support in `librbd`.

**Comment by elemental-lf** [comment]
@adambmedent I think you could give this branch a try: https://github.com/elemental-lf/benji/tree/rbdaio. It adds a new I/O module named `rbdaio` which uses the AIO functions in `librbd`, so you have to adjust your configuration. In my tests I haven't seen any big performance gains, about 10 to 20%. And this is with all blocks cached in the read cache. Depending on the load of my production Ceph cluster I'm observing restore speeds around 180 to 240MiB/s with `rbdaio`, a little less with `rbd`. This is still much, much more than your 15MiB/s, so maybe you also have problems elsewhere.
I suggest setting `simultaneousRead` and `simaltaneousWrites` to about 15. It seems that at least with my Ceph configuration there is an upper bound on the number of outstanding I/O imposed by `librbd` and anything greater than 15-20 doesn't make much of a difference. Please report back your findings!

**Comment by adambmedent** [comment]
I am in the process of moving my ceph cluster into production.  I should hopefully get to testing this soon.

**Comment by elemental-lf** [comment]
FYI: I've merged the changes into `master` in the meantime.

**Comment by elemental-lf** [comment]
@adambmedent could you test the new i/o module yet?

**Comment by adambmedent** [comment]
Just getting back to this now.  

I updated my Benji install to 0.6.0.

(benji) [root@ceph-benji ~]# benji version-info
    INFO: $ /usr/local/benji/bin/benji version-info
    INFO: Benji version: 0.6.0.
    INFO: Configuration version: 1, supported >=1,<2.
    INFO: Metadata version: 1.1.0, supported >=1,<2.
    INFO: Object metadata version: 1.0.0, supported >=1,<2.

However I don't seem to have the module.

(benji) [root@ceph-benji ~]# benji ls -s
    INFO: $ /usr/local/benji/bin/benji ls -s
   ERROR: ModuleNotFoundError: No module named 'benji.io.rbdaio'

Anything special I need to do?

**Comment by elemental-lf** [comment]
You need to install the `master` branch to get the new module.

**Comment by adambmedent** [comment]
Ahhh ok, my mistake.  

Quite the difference for me.  I am now seeing roughly 100-125MB/s in writes during the restore.  Speeds are now on par when I do a benji file restore.  

This is fantastic.

**Comment by adambmedent** [comment]
Definitely a huge improvement for me.

INFO: Successfully restored version V0000001259 in 39m 11s with 119.6MiB/s.

**Comment by elemental-lf** [comment]
Thank you for reporting back! I'm glad that the speed improved so much for you. But I'm still puzzled as to why I'm not seeing much of a difference either way. This is a question of another day, I'm going to close this issue. (For the time being I'll leave in both modules so that the users can choose.)
