### ISSUE TITLE
[Question] Why is the `kdfIteration` setting listed as a base64 encoded string?

### ISSUE THREAD

**Issue by ArcticSnowman** [elemental-lf/benji#42]
Why is the `kdfIteration` setting listed as a base64 encoded string?

```
name: kdfIterations

type: binary string encoded with BASE64

default: none

Sets the number of iterations for the key derivation function.
```

Surely this should only be a integer...

**Comment by ArcticSnowman** [comment]
Created PR #43 to fix documentation

**Comment by elemental-lf** [comment]
Yeah, one of those cut & paste errors. Thanks for the PR, I just merged it.
