### ISSUE TITLE
Add storage option to restore with --database-backend-less option

### ISSUE THREAD

**Issue by adambmedent** [elemental-lf/benji#48]
When restoring a version with --database-backend-less option which resides on storage outside of the default storage defined in /etc/benji/benji.yaml it fails.  Would it be possible to add an option to the restore with --database-backend-less to define the storage which the version resides?

**Comment by elemental-lf** [comment]
This was actually an oversight on my part when introducing multiple storages. I just pushed 5d02b9ef392e7b9bdae49e9ab6659a4bf9ed3c2f. It adds the ``--storage`` option to the restore command for database-less restores. I actually also changed the long option name to ``--database-less`` as it was too long even for my taste and I've been replacing all occurrences of database backend with database elsewhere too.
