### ISSUE TITLE
Error when trying to init the database

### ISSUE THREAD

**Issue by johnnybee** [elemental-lf/benji#51]
Hello,

i have setup an CentOS7 VM and installed benji without a container. Everything works well, but when I try to init the database, I get the following error:

`{'event': 'Uncaught exception', 'level': 'error', 'timestamp': 1567076555.5844882, 'file': '/usr/local/lib/python3.6/site-packages/benji/logging.py', 'line': 169, 'function': 'handle_exception', 'process': 2333, 'thread_name': 'MainThread', 'thread_id': 140201858869056, 'exception': 'Traceback (most recent call last):\n  File "/usr/local/bin/benji", line 10, in <module>\n    sys.exit(main())\n  File "/usr/local/lib/python3.6/site-packages/benji/scripts/benji.py", line 292, in main\n    config = Config()\n  File "/usr/local/lib/python3.6/site-packages/benji/config.py", line 168, in __init__\n    if version_obj not in VERSIONS.configuration.supported:\n  File "/usr/local/lib/python3.6/site-packages/semantic_version/base.py", line 642, in __contains__\n    return self.match(version)\n  File "/usr/local/lib/python3.6/site-packages/semantic_version/base.py", line 630, in match\n    return self.clause.match(version)\n  File "/usr/local/lib/python3.6/site-packages/semantic_version/base.py", line 745, in match\n    return all(clause.match(version) for clause in self.clauses)\n  File "/usr/local/lib/python3.6/site-packages/semantic_version/base.py", line 745, in <genexpr>\n    return all(clause.match(version) for clause in self.clauses)\n  File "/usr/local/lib/python3.6/site-packages/semantic_version/base.py", line 910, in match\n    return version >= self.target\n  File "/usr/local/lib/python3.6/site-packages/semantic_version/base.py", line 467, in __ge__\n    return self.precedence_key >= other.precedence_key\nTypeError: \'>=\' not supported between instances of \'NoneType\' and \'int\''}`

Could please someone explain me, what to do? Thank you very much.

**Comment by wanthalf** [comment]
Exactly the same problem here... Ubuntu 18.04 with venv.

**Comment by wanthalf** [comment]
The quick workaround is to comment the lines 168-169.

Still I had some more trouble with the ceph.sh script. It does not do anything by itself, just defines functions, so I had to add "benji::backup::ceph $@" to the end. Also, it wont't work (=call benji correctly) unless you also give it some "labels".

**Comment by elemental-lf** [comment]
@johnnybee Thanks for reporting this. Yesterday and today four new versions of `semantic-version` which is a dependency of Benji were released. The step from 2.6.0 to 2.7.0 broke Benji for some reason. I'll have to look into this. For the time being I've pinned the version. You can also force the install of version 2.6.0 with `pip install --upgrade semantic-version==2.6.0` and the error shouldn't occur anymore.
@wanthalf The script code in `scripts/ceph.sh` is meant as a collection of functions and as such primarily as an example on how to call Benji  in the context of Ceph as use cases vary significantly. If you found a problem with the functions I'd welcome a PR with a fix.

**Comment by elemental-lf** [comment]
I've released 0.7.1 with the interim fix for this. I'll keep this issue open until I've found out why the newer versions of `semantic-version` break Benji.

**Comment by johnnybee** [comment]
@elemental-lf Thank you for your fast Bugfix and good luck for your search!

**Comment by wanthalf** [comment]
I am very sorry, but after having successfully avoided more complex bash scripting for more than 25 years, its syntax is still a puzzle for me. I've spent a few hours trying something like `[ -z $VERSION_LABELS ] && LABELS="" || LABELS="$(printf -- "-l %s " "${VERSION_LABELS[@]}")"` and it works as a pure string, but inserting `"$LABELS"` to the benji call does not work anymore. I could write this in at least 4 or 5 other languages without problems, but bash behaves obviously always completely differently than anything else I am used to. So, I know you are not here to teach me bash scripting, but I suppose you can fix it within 5 seconds yourself, unlike me. ;-)
