### ISSUE TITLE
Benji and ZFS/Zvol

### ISSUE THREAD

**Issue by adambmedent** [elemental-lf/benji#55]
What do you think about using benji to backup a zvol block device?

**Comment by elemental-lf** [comment]
I haven't tried that yet but I see nothing that should prevent it from working. As long as you have a block device. If you try it out and it works, please report back in this issue. If there are any problems I'd like to address them in new separate issues. Thanks!

**Comment by elemental-lf** [comment]
@adambmedent have you tried  backing up a zvol yet?

**Comment by adambmedent** [comment]
Unfortunately ive had other projects holding me back.  It might be a bit of time before I get to this one.

**Comment by elemental-lf** [comment]
I'm closing this for now.
