### ISSUE TITLE
Chances for CentOS-7 RPM/Repository

### ISSUE THREAD

**Issue by akotobi88** [elemental-lf/benji#64]
Hi,

Currently Benji deployed and configured by the tutorial in documentation, but would that be possible to have it in RPM/Repository way? As back-end servers do not have all the access to internet and only cherry-picked repositories in managed way are available.
The urgency rises by having CEPH back up in a fast way along with having metadata.

Thanks
Amjad

**Comment by elemental-lf** [comment]
Not at this time, at least not from me. I'm sorry. I might consider integrating automatic RPM builds via Travis CI if someone wants to contribute but see the next paragraph.

I have experimented with packing Benji into a standalone executable with PyInstaller with some success (see https://github.com/elemental-lf/benji/blob/master/pyinstaller/benji.spec). It might be worth to investigate this further, especially as it would be Linux distribution agnostic. From the top-level directory of the repository you can build a standalone executable with:
```bash
pyinstaller -y --workpath pyinstaller/build --distpath pyinstaller/dist pyinstaller/benji.spec
```
On my system the executable is  only 26MBs. An open issue is the interaction with the external Python packages `rbd` and `rados` which I haven't tested yet. So there probably is some work to be done still but it sounds more promising than building packages for several different Linux distributions.

Last but not least there's the container image which can be used with any OCI compliant container runtime which almost any system has nowadays. It includes all Ceph dependencies and should work with Jewel and above I think. By wrapping it into a shell script and with some bind mounts it can be used as if it were natively installed. Again contributions of such a script would be welcome.
