### ISSUE TITLE
Database upgrade to 0.8.0

### ISSUE THREAD

**Issue by adambmedent** [elemental-lf/benji#66]
In the process of attempting to upgrade to 0.8.0 and so far it hasn't gone so well.  

The VM has very minimal CPU load and 0 IO wait.  It has 16 cores with 75G of ram and its using postgres as the database.    

Our current database size is roughly 29GB.  I even gave the VM enough ram so I could use vmtouch and load all of the pgsql directory into ram.  This eliminated all my reads coming from disk but hasn't really helped speed anything up.  

It feels like writes are the limiting factor but the system isn't showing any signs that its even remotely close to running out of gas.  Is there anything within benji that could be limiting this?

I can certainly give this a go on some SSD storage, but it honestly doesn't look like that is going to help either.  

Appreciate the input!

**Comment by adambmedent** [comment]
Cut over to a SSD and things are going slightly faster but not a ton.  I can usually spot a bottle neck pretty quickly, but there simply isn't much going on.  

A bit nervous for this process moving forward as my database gets bigger.

**Comment by adambmedent** [comment]
After 24 hours the process finally completed.  However all my backups are now failing and it seems I have some issues I need to figure out.  

Still seems unreasonable that a 29G database took a bit over 24 hours to upgrade on a SSD with the database fully cached in ram.

**Comment by adambmedent** [comment]
I was able to get my scripts fixed up so backups are moving again.  

Im thinking the uid no longer using V00000### is expected based on the release notes but I am not totally sure.  Not a huge deal I guess.     

Biggest issue was the time to upgrade.  Just doesn't seem reasonable.

**Comment by elemental-lf** [comment]
This is expected. The database migration process to `0.8.0` is dead slow and could be optimized a lot. But I didn't want to spent too much time on it as Benji is still pre-release software. There are three reasons why I'm providing database migrations at all:
* to familiarize myself with the process of writing migrations
* to migrate my own smallish database
* and as a courtesy to early adopters like you.

Please keep that in mind. Thanks!

**Comment by adambmedent** [comment]
Well I certainly appreciate it.  Do you think Benji is going to make it to a stable release any time soon?

**Comment by elemental-lf** [comment]
There is no set date or deadline, sorry. But it is really helpful that people like you are continuously testing Benji and it increases my confidence in the data integrity and the reliability of the backup and restore process. Your and other people's testing constitutes a great part of the way to a stable release. That being said we could use some more testers.

**Comment by adambmedent** [comment]
Well if the proxmox admins are ok with it, maybe we can pick up a few from this :).

https://forum.proxmox.com/threads/any-proxmox-ceph-users-interested-in-helping-test-benji.63027/

**Comment by elemental-lf** [comment]
Thank you for the kind words in your forum post. Drawing more attention to the project is definitely the way to go and a thing that I'm not very good at.
