### ISSUE TITLE
Questions about changing transforms and multiple storages

### ISSUE THREAD

**Issue by elemental-lf** [elemental-lf/benji#68]
Yes, this is definitely the case. I see this in the offsite backup where i use zstandard compression (level 1 currently).

I just hesitate to change the configuration for the (local) production backups, because I'm unsure if the information about compression and encryption is persisted to the stored blocks. 

What would happen if i add compression to the current configuration which results in some blocks of one backup set to contain compressed and uncompressed blocks?

Also I could not find information on how to configure an additional storage (offline-storage) on the same benji.yaml and database.

Therefore I used a separate benji.yaml and database. I just was not completely sure if two different storages would be supported by one database. I did not want to risk putting one block on only one of the storages which could result in missing blocks during restore in the case of losing one of the two backup storage locations.

I guess it would be handled correctly as there is a column in benji ls giving the storage used, but I needed to make it 100% safe ;-)

_Originally posted by @wech71 in https://github.com/elemental-lf/benji/issues/67#issuecomment-576689365_

**Comment by elemental-lf** [comment]
> I just hesitate to change the configuration for the (local) production backups, because I'm unsure if the information about compression and encryption is persisted to the stored blocks.

Yes, it is persisted in each block's meta-data (the .meta files/objects). As you currently haven't enabled any transforms you can directly look at the meta-data files and see for yourself. It's JSON formatted.

So to enable compression you need to add a `zstd` transform to the configuration and add it to the list of active transforms for the respective storage. It will be used for all newly written blocks. It is important to not remove the transform as long as there are blocks using it even when you've deleted it from the list the of active transforms again. In addition you shouldn't change a transform after it has been used. For example if you change the encryption materials old blocks can't be decrypted any more. Define a new transform if you want to change any of a transform's parameters. There is currently one exception: It is safe to change the compression level after the fact because it is only used during compression and not a required piece of information during decompression.

> What would happen if i add compression to the current configuration which results in some blocks of > one backup set to contain compressed and uncompressed blocks?

There'll be a mix of compressed and uncompressed blocks in the storage. Some of the uncompressed blocks will age out over time but some will probably stay for a long while.

It would be possible (and it's on the long-term TODO list) to rewrite old blocks in the storage and apply changed or new transforms to them. Think: key rollover or your use case of enabling compression on an existing storage. But this hasn't been implemented yet.

> Also I could not find information on how to configure an additional storage (offline-storage) on the same benji.yaml and database.

> I did not want to risk putting one block on only one of the storages which could result in missing blocks during restore in the case of losing one of the two backup storage locations.

You can define multiple storages inside the same configuration using the same database. Without a `--storage` argument  to `benji backup` the default storage will be used. A specific version's blocks are always in only one storage. The deduplication is per storage. So if you use two storages there will be a duplication of blocks between storages but deduplication of blocks inside the same storage.

**Comment by wech71** [comment]
Thank you very much vor your exhaustive explanation :-)

This totally makes sense ;-)
