### ISSUE TITLE
Space usage issues on backup storage

### ISSUE THREAD

**Issue by elemental-lf** [elemental-lf/benji#69]
We also run benji for more than a year now in a spliced setup with two independent backup destination server saving files locally. Currently we upgraded to the latest version of benji, the migration took about 2 hours. Also i now enabled compression at level 3.

The database size is about 5gb for each server 
It runs very good and fast. We built a Django operation tooling around it and backup a Ceph System for VM Images (Xenserver)

But now to one problem which is getting bigger at the moment:
We are running out of backup space.

The backups shown in benji with bytes_written sum up to 3,4TB (server-1) and 2,4TB (server-2).
But the absolute space used in the data directory is 8,8TB (server-1) and 7,1TB (server-2)

Seems like there is some kind of lost blocks left in this directory and i could not find out how to diagnose or cleanup. On one server we're running batch-scrub and i'll try the cleanup afterwards but i don't think this will solve the problem. Do you have any advices how to manage that situation?

Is there any check that looks for files not in the database?

_Originally posted by @blodone in https://github.com/elemental-lf/benji/issues/67#issuecomment-581155760_

**Comment by elemental-lf** [comment]
Comment by @wech71 (originally posted in #67):

Did you run
benji enforce "list of retention specifications"
before
benji cleanup

cleanup only removes blocks which are marked as unused by benji enforce.

**Comment by elemental-lf** [comment]
Comment by @blodone (originally posted in #67):

Yes we run this event daily before cleanup.

The size reported of every backup available (bytes_written) in benji DB is about 3 x smaller than the actual disc size used. How can that be? There must be some kind of data in the folder that does not belong to the backups anymore. e.g. from failures in previous backups or failures from previous cleanup.

**Comment by elemental-lf** [comment]
@blodone I think your calculation is based on incorrect assumptions. You're missing all the `bytes_written` of versions which have been removed already (for example by `benji enforce`). Their blocks might by still in use by versions currently in the database. Even if you would take into account `bytes_deduplicated` as well, the number would still be wrong as Benji won't see a lot of blocks again because Ceph lists them as unchanged. The only way to calculate the space usage of blocks based on the database is to produce a list of all distinct block uids (the pair uid_left, uid_right) and their sizes and then sum up all the sizes. This still wouldn't account for space used by the version metadata backups and the metadata of each block.

I won't rule out the possibility that Benji is leaking blocks somewhere, but I'd need some more concrete evidence for this. There currently is no feature to find lost blocks in the storage. It will be (re)implemented eventually I think.

**Comment by elemental-lf** [comment]
I forgot to mention that compression and to a much lesser extent also encryption factor into this as the database records only the original size. 
NB if you've just recently enabled compression there will still be tons of uncompressed blocks. And a lot of them will stay around as long as they're used.

**Comment by blodone** [comment]
Thanks for the response and moving it to an issue. Yes that might be the issue, I forgot to calculate with the deleted versions still sharing blocks for other versions. Some feature to find out what backups are using the most of the space or something like that would help diagnosing if the space usage is ok.

**Comment by elemental-lf** [comment]
>  Some feature to find out what backups are using the most of the space or something like that would help diagnosing if the space usage is ok.

Producing a meaningful number (per version)  is not really possible due to the deduplication that is happening. A block might be shared by any number of versions. If Benji would account a shared block for each versions which uses it the usage would be greatly overestimated. On the other side if Benji would account a shared block only to one version it begs the question to which? They are all the same. And if that version would be deleted, this block would have to be accounted to another version. So this version might grow as a side effect of deleting a version, that's not intuitive. In summary both approaches don't produce information useful to the user and the second one is probably also hard to implement. But I'm open to suggestions.

**Comment by elemental-lf** [comment]
I'm closing this as the original misunderstanding of the way the statistics counters work seems to be cleared up. If you have any further issues or questions, please don't hesitate to open a new issue. Thanks!
