### ISSUE TITLE
Benji cleanup is not working?

### ISSUE THREAD

**Issue by kvaps** [elemental-lf/benji#73]
Hi, I'm new user of benji, but I trying to understand the logic:

I had free server and just created 20 backups, then removed all of them using
```bash
benji rm -f <uid>
```
command, then run:
```bash
benji cleanup
```
but it's reported:
```
    INFO: $ /benji/bin/benji cleanup
    INFO: Cleanup: Cleanup finished. 0 false positives, 0 data deletions.
```

The backups are missing:
```
    INFO: $ /benji/bin/benji ls
+------+-----+--------+----------+------+------------+--------+-----------+---------+
| date | uid | volume | snapshot | size | block_size | status | protected | storage |
+------+-----+--------+----------+------+------------+--------+-----------+---------+
+------+-----+--------+----------+------+------------+--------+-----------+---------+
```

But data folder still contains some data blocks:
```bash
# du -hs /data/benji-data/
18G	/data/benji-data/
```

What am I doing wrong?

**Comment by olifre** [comment]
Hi,

this is [known behaviour](https://benji-backup.me/cleanup.html): To prevent race conditions, blocks are only removed by `cleanup` if they are marked for deletion for at least one hour ;-). 

Cheers!

**Comment by kvaps** [comment]
Awesome! Thanks for explanation!

**Comment by kvaps** [comment]
But is there any option to force cleanup these blocks without waiting 1 hour? Eg. it makes sense when storage is running lack of space

**Comment by olifre** [comment]
I don't think any such option is there yet, apart from calling the `cleanup` function manually and adjusting `dt`:
https://github.com/elemental-lf/benji/blob/28b2b604c718bb93f95f6958e12b8065f1a64382/src/benji/benji.py#L976
which is what the smoke tests are doing. 

@elemental-lf What do you think?

**Comment by elemental-lf** [comment]
I'm not sure if I like this idea because it has the potential of losing data if parallel backups are in progress. So such an option would either need to output a large warning before proceeding with the cleanup or it should not be implemented at all. I'm leaning in the latter direction.
