### ISSUE TITLE
LINSTOR backup-operator for Kubernetes

### ISSUE THREAD

**Issue by kvaps** [elemental-lf/benji#77]
Hi, I'm going to develop a Kubernetes operator to performing a backup for [LINSTOR](https://www.linbit.com/linstor/) devices using Benji Backup, and I wanted to decide the next logic for this operator.

The main design is:

![benji](https://user-images.githubusercontent.com/7556217/79977764-111cfb80-849f-11ea-9bbe-f489f01ea5bc.png)

Thus I'm going to run multiple instances of benji in same time on different nodes but with same common database to minimise the network usage due deduplication. I'm expecting that Benji-backup will read the block device and compare each block checksum with information in database. If block is already existing on server it will be omitted.

Since benji have no server part, only client one, do I right understand that it shouldn't be a problem to run multiple instances in same time?

**Comment by elemental-lf** [comment]
* Yes, deduplication works via the database.
* And yes, you can run multiple instances of Benji simultaneously.
* Please be aware that I've been working on a Kubernetes operator myself for some time now. Unfortunately progress is slow as most of the work is done in my free time and I've changed the design several times in the process. The work-in-progress branch is `k8s-operator`. It still requires a few days of work to be actually usable and there are multiple lose ends currently. 
The operator creates Kubernetes jobs to do the actual backups and I think the pods of a job  could be made to schedule on specific nodes to guarantee data locality. 
Apart from the Ceph and Rook support I'm planning to include a generic CSI backup mode based on CSI snapshots. But there is a start to make this even more generic to include other SDS solutions.
 Restores will be storage agnostic by using the block volume support that has been introduced into Kubernetes some time ago. 
There are a number of custom resources: one representing versions, but also ones to schedule backups and start restores.
It's based on the Kopf operator framework: https://github.com/zalando-incubator/kopf.

**Comment by kvaps** [comment]
>-    Yes, deduplication works via the database.
>-    And yes, you can run multiple instances of Benji simultaneously.

Awesome!

> The operator creates Kubernetes jobs to do the actual backups and I think the pods of a job could be made to schedule on specific nodes to guarantee data locality.

I was thinking about the same design :)

>  I'm planning to include a generic CSI backup mode based on CSI snapshots. But there is a start to make this even more generic to include other SDS 

That's not a bad idea! I'll consider to go this way.

The only problem which I trying to solve now is the need to develop common solution to different platforms, eg. we're using OpenNebula and Kubernetes with the LINSTOR.

Thus I face a choice:
- to develop two different storage-agnostic backup solutions for OpenNebula and Kubernetes
- to stick LINSTOR as the main storage platform and develop common backup solution for any platform which uses LINSTOR.

The second case is easier and better to support storage-specific features, I'd like to go this way.

> Restores will be storage agnostic by using the block volume support that has been introduced into Kubernetes some time ago.

That's not a bad idea! I'll consider to go this way.

BTW I think even backup process could use the same block volumes feature created via kubernetes snapshots.

> It's based on the Kopf operator framework: https://github.com/zalando-incubator/kopf.

I have not experience with Kopf yet, but I was really like to use [kubebuilder](https://github.com/kubernetes-sigs/kubebuilder) to achieve that.

Thanks for  your answers! I will take them into service!

**Comment by elemental-lf** [comment]
>     * to develop two different storage-agnostic backup solutions for OpenNebula and Kubernetes 
>     * to stick LINSTOR as the main storage platform and develop common backup solution for any platform which uses LINSTOR.

You lost me there. You're taking about a Kubernetes operator. How will it work with OpenNebula? I must admit that I know next to nothing about OpenNebula. In my recollection it's something like OpenStack. How would a Kubernetes operator be a "common backup solution for _any_ platform which uses LINSTOR" in the case that the platform isn't Kubernetes?

Storage specific solutions will always make a lot of sense when the storage provides some extra information like which blocks are actually used or are unchanged between snapshots. Benji supports all of these if someone writes an adapter that generates the hints file for Benji (and writes an IO module if necessary). I know that such optimizations would be possible for LVM volumes. Does DRBD have something similar?

Anyway, even if you decide to develop your own operator and it sounds like that, I'd welcome any suggestions or discussions about the topic. I would expect that we'd face the same obstacles in some areas and so synergies might emerge. And of course code and documentation contributions are welcome, too... 😉

**Comment by kvaps** [comment]
>You lost me there. You're taking about a Kubernetes operator. How will it work with OpenNebula? I must admit that I know next to nothing about OpenNebula. In my recollection it's something like OpenStack.

Oh my bad, I forgot to say that I'm running [OpenNebula in Kubernetes](https://github.com/kvaps/kube-opennebula), that's simplifies the deployment and unifies the management.
But anyway, you're right I shouldn't develop an kubernetes-operator to solve non-kubernetes stuff.

>Storage specific solutions will always make a lot of sense when the storage provides some extra information like which blocks are actually used or are unchanged between snapshots. Benji supports all of these if someone writes an adapter that generates the hints file for Benji (and writes an IO module if necessary).

This is really cool that Benji could be so simple extendable!

> I know that such optimizations would be possible for LVM volumes. Does DRBD have something similar?

DRBD itself don't, but LINSTOR is more complex platform. It uses LVM or ZFS volumes as backend for DRBD. Snapshots are working, but send/recieve operations are not implemented yet.

I can quote @Philipp-Reisner here:

> Right we will build snapshot (delta) shipping into LINSTOR. On ZFS volumes based on zfs send / receive on LVM thin based on https://github.com/LINBIT/thin-send-recv
> I plan that we will have a linstor release with that before the end of May (2020 :slightly_smiling_face: ).

As about operator, I changed my mind a bit. For now I'm planning to have just simple ansible-playbook with same simple logic:

- Get all the resources created in LINSTOR
- For each resource do:
  - Create snapshot
  - Run Kubernetes job via [k8s module](https://docs.ansible.com/ansible/latest/modules/k8s_module.html) on same node where resource is located.  It will perform backup for the snapshot using benji.
  - Wait until job is finished
  - Delete snapshot

I'm planning to run this playbook using CronJob in Kubernetes.

**Comment by elemental-lf** [comment]
@kvaps, I think I understand now: You also have LINSTOR volumes which are not directly represented in Kubernetes as PersistentVolumes  because they are provisioned and used by OpenNebula. Correct?

> DRBD itself don't, but LINSTOR is more complex platform. It uses LVM or ZFS volumes as backend for DRBD. Snapshots are working, but send/recieve operations are not implemented yet.
> 
> I can quote @Philipp-Reisner here:
> 
> > Right we will build snapshot (delta) shipping into LINSTOR. On ZFS volumes based on zfs send / receive on LVM thin based on https://github.com/LINBIT/thin-send-recv
> > I plan that we will have a linstor release with that before the end of May (2020 slightly_smiling_face ).

Ah, I see! The code in `thin_send_diff` (https://github.com/LINBIT/thin-send-recv/blob/c48c568055c14d1fa893ac110cadb8c1ded32aea/thin_send_recv.c#L156)
goes in the same direction as the code that would be needed to produce the JSON hints file for Benji I think. I wasn't aware that `thin_delta` and co existed. Learn something new every day. `lvmsync` also has code that tries to figure out the difference between two snapshots. But it directly parses the binary metadata. It also handles normal LVM volumes: https://github.com/mpalmer/lvmsync/blob/4b3bf6e924d16ec4e187ac19889b76747eb096ae/lib/lvm/snapshot.rb#L16.

> As about operator, I changed my mind a bit. For now I'm planning to have just simple ansible-playbook with same simple logic:

That's  sounds roughly similar to what the current released version of Benji does for Ceph and what I've been using in production for quite some time now: Create a bunch of CronJobs via Helm, the jobs determine the PVCs to backup via label selector, handle the snapshots and the backup via Benji itself.

As your original questions are answered I'm going to close this issue.

**Comment by kvaps** [comment]
> @kvaps, I think I understand now: You also have LINSTOR volumes which are not directly represented in Kubernetes as PersistentVolumes because they are provisioned and used by OpenNebula. Correct?

Yes exactly!

> Create a bunch of CronJobs via Helm, the jobs determine the PVCs to backup via label selector, handle the snapshots and the backup via Benji itself.

Thanks for sharing your thoughts!
