### ISSUE TITLE
benji-k8s: crontab is not executed

### ISSUE THREAD

**Issue by mgiammarco** [elemental-lf/benji#81]
Hello,
I am trying benji-k8s, I have tried version 0.5.0 and now latest version.
It seems that crontab support in latest version is missing.
I do not see cron package installed or crond running.
Can you help me?
Thanks,
Mario

**Comment by elemental-lf** [comment]
In version `0.8.0` Benji for Kubernetes uses the Kubernetes' `CronJob` workload controller to schedule backup jobs. For this to work Benji needs to be deployed with Helm or you need to create the `CronJobs` manually. See https://github.com/elemental-lf/benji/blob/5d5f2dc18eaa92019793fa30c93ae7a2a87b4253/charts/benji-k8s/values.yaml#L32-L48 and https://github.com/elemental-lf/benji/blob/v0.8.0/charts/benji-k8s/templates/cronjobs.yaml.

I'm still working on the Benji operator for Kubernetes but I'm not sure when it will be ready. The operator will use custom resources to define backup schedules.

**Comment by mgiammarco** [comment]
Ok so to deploy a benji in docker (non k8s)
