### ISSUE TITLE
Issues with enforcement

### ISSUE THREAD

**Issue by elemental-lf** [elemental-lf/benji#83]
Looks like there are still some issues with enforcement.  

[root@udarchive-benji ~]# /usr/local/benji/bin/benji enforce latest1,days525 --dry-run
    INFO: $ /usr/local/benji/bin/benji enforce latest1,days525 --dry-run
    INFO: Removing versions: vm-278-disk-0-rbm1dy, vm-280-disk-0-fue563.
    INFO: Dry run, won't remove anything.

[root@udarchive-benji ~]# /usr/local/benji/bin/benji ls | grep vm-278-disk-0-rbm1dy
    INFO: $ /usr/local/benji/bin/benji ls
| 2020-05-27T01:09:29 | vm-278-disk-0-rbm1dy | vm-278-disk-0 | benji-ccs-2020-05-27T01:09:26    |  100.0GiB |     4.0MiB |  valid  |   False   | benji-ccs    |                                      [root@udarchive-benji ~]# /usr/local/benji/bin/benji ls | grep vm-280-disk-0-fue563
    INFO: $ /usr/local/benji/bin/benji ls
| 2020-05-27T01:09:44 | vm-280-disk-0-fue563 | vm-280-disk-0 | benji-ccs-2020-05-27T01:09:41    |  100.0GiB |     4.0MiB |  valid  |   False   | benji-ccs    |

Both of these versions are from 5-27-20, not sure why benji is seeing them as 525 days old.  Any ideas?

_Originally posted by @adambmedent in https://github.com/elemental-lf/benji/issues/30#issuecomment-652361126_

**Comment by elemental-lf** [comment]
Without seeing all present versions it is impossible to tell why something is deleted or not. But in your case I think that you have the meaning of `latest1,days525` wrong. It means to keep the youngest version (`latest1`) and then keep 525 versions, one for each calendar day, starting with the current day (`days525`). All other versions of the current day will be deleted. If you want to keep any of those you need to add `hoursXX` to your specification which takes precendence.
The syntax was borrowed from the original implementation of the algorithm and I must admit that it can be confusing. There are some examples in the [documentation.](http://benji-backup.me/enforce.html#policy-specification).

**Comment by adambmedent** [comment]
You Sr are correct, I had 2 versions for the same date.  Woooops.  This can be closed.
