### ISSUE TITLE
Helm K8S and ClientIdentified

### ISSUE THREAD

**Issue by renatogalera** [elemental-lf/benji#85]
Hello,

I'm having trouble using the k8s version of benji, we dont use admin "id" account. 

Inside the container I can make backups using

`benji backup rbd:..`

But, ClientIdentified != admin not working in script **benji-backup-pvc**.

We took a look at ceph.py and it doesn't have a variable for listing objects in different users ids.

Am I doing something wrong?

Thank You!

**Comment by renatogalera** [comment]
I changed ceph.py, and working

`subprocess_run(['rbd', `

to

`subprocess_run(['rbd', '--id=eveo-kubernetes',`

and

`benji_args.extend([f'{pool}:{pool}/{image}@{snapshot}', volume])`

to 

`benji_args.extend([f'rbd:{pool}/{image}@{snapshot}', volume])`

**Comment by elemental-lf** [comment]
@renatogalera I'm glad that you found a solution. I still have some information that might be useful to you. With two recent commits (https://github.com/elemental-lf/benji/commit/7e714f853a7a30705f7a1643d7838969da6f05d7, https://github.com/elemental-lf/benji/commit/a442b00e9b667bd1c1a7ecfb5da70fafb977c6f7) it became possible to supply arbitrary Ceph configuration settings via the URL, this includes credentials and the client identifier. See https://benji-backup.me/configuration.html#i-o-module-rbd for documentation. These changes are include in [v0.9.0](https://github.com/elemental-lf/benji/releases/tag/v0.9.0).
