### ISSUE TITLE
Restores to RBD volumes slow

### ISSUE THREAD

**Issue by adambmedent** [elemental-lf/benji#87]
Last week we had a catastrophe with our Ceph cluster.   Benji came to the rescue and we were able to restore all the RBD's.  The only issue is that the throughput of a single restore was pretty bad (15-20MB/s).  

When we started restoring data I had simultaneousReads: 5 and simultaneousWrites: 5 under the rbd module.  I tried to take them to 10, then 15 and then 20 with absolutely no change in performance.  

With 10-15 restores going the benji backup storage would be reading at 200-275MB/s and the Ceph cluster would be writing at 200-275MB/s to match, so I know both the backup storage and the ceph storage have the performance.   

I don't seem to have this issue with restoring to a file, only rbd.  Any suggestions or ideas on how to get restore performance to improve for rbd?  Including my config as well.  

`configurationVersion: '1'
databaseEngine: postgresql://benji:xxxxx@localhost:5432/benji
defaultStorage: benji-ccs
logFile: /var/log/benji.log

storages:
  - name: benji-ccs
    storageId: 1
    module: file
    configuration:
      simultaneousReads: 20
      simultaneousWrites: 20
      path: /benji-ccs

  - name: benji-bunker
    storageId: 2
    module: file
    configuration:
      simultaneousReads: 20
      simultaneousWrites: 20
      path: /benji-bunker

ios:
  - name: file
    module: file
    configuration:
      simultaneousReads: 20
      simultaneousWrites: 20

  - name: rbdaio
    module: rbdaio
    configuration:
      simultaneousReads: 20
      simultaneousWrites: 20
      cephConfigFile: /etc/ceph/ceph.conf
      clientIdentifier: admin
      newImageFeatures:
      - RBD_FEATURE_LAYERING
      - RBD_FEATURE_EXCLUSIVE_LOCK
      - RBD_FEATURE_STRIPINGV2
      - RBD_FEATURE_OBJECT_MAP
      - RBD_FEATURE_FAST_DIFF
      - RBD_FEATURE_DEEP_FLATTEN

  - name: rbd
    module: rbd
    configuration:
      simultaneousReads: 20
      simultaneousWrites: 20
      cephConfigFile: /etc/ceph/ceph.conf
      clientIdentifier: admin
      newImageFeatures:
      - RBD_FEATURE_LAYERING
      - RBD_FEATURE_EXCLUSIVE_LOCK
      - RBD_FEATURE_STRIPINGV2
      - RBD_FEATURE_OBJECT_MAP
      - RBD_FEATURE_FAST_DIFF
      - RBD_FEATURE_DEEP_FLATTEN`

**Comment by elemental-lf** [comment]
First of all, I'm delighted to hear that the data recovery with Benji worked as expected (albeit a bit slow). Thanks for the feedback!
Regarding the speed we had this discussion before, see https://github.com/elemental-lf/benji/issues/40. You reported much improved restore speeds with the `rbdaio` module. What module where you using for your restores now?

**Comment by elemental-lf** [comment]
I'd like to add that it is quite possible that the original `rbd` module has solvable speed issues. But if the `rbdaio` performs significantly better, I'd rather promote the `rbdaio` module to be the new default. That was the original plan anyhow.

**Comment by adambmedent** [comment]
> First of all, I'm delighted to hear that the data recovery with Benji worked as expected (albeit a bit slow). Thanks for the feedback!
> Regarding the speed we had this discussion before, see #40. You reported much improved restore speeds with the `rbdaio` module. What module where you using for your restores now?

Dohhh, man I totally forgot about using rbdaio.  Night and day difference between the two.  With rbdaio I can now restore a single version at well over 200MB/s.

This was a fantastic DR test at the very least.  Benji really stepped up to the task.    

As usual I appreciate the input.

**Comment by elemental-lf** [comment]
That's great! I'm going to close this issue then.
