### ISSUE TITLE
invalidating object map

### ISSUE THREAD

**Issue by wanthalf** [elemental-lf/benji#88]
Lately, we upgraded Ceph to version 15.2.4 and shortly after that we had a blackout, which actually caused a restart of all servers. Since then we received lots of complaints about "object-maps" with every benji backup of a RBD image. So, I turned on "exclusive-lock" and "fast-diff" and rebuilt object-map for every RBD image. Since then I am receiving the following message for every benji RBD image backup:

```
2020-08-24T06:25:10.451+0200 7f0b857fa700 -1 librbd::object_map::InvalidateRequest: 0x7f0b8000a690 invalidating object map in-memory
2020-08-24T06:25:10.451+0200 7f0b857fa700 -1 librbd::object_map::InvalidateRequest: 0x7f0b8000a690 invalidating object map on-disk
2020-08-24T06:25:10.451+0200 7f0b857fa700 -1 librbd::object_map::InvalidateRequest: 0x7f0b8000a690 should_complete: r=0
```

Is it a real problem limiting the functionality of the backups, or just natural part of the process? Is it a problem of Ceph and the unexpected blackout causin g some corrpution, or a problem of Benji and some new feature/issue of Ceph version 15?

I wonder whether Benji used the object-maps before, since there were never any reports about any problems of this kind, and even the features mentioned above were probably never turned on before (so there were no object maps at all?).

**Comment by elemental-lf** [comment]
I think you need to take your questions to the Ceph developers. Benji has no direct knowledge of the object maps and about what `librbd` does behind the scenes. It just reads the RBD images and snapshots via the supplied API. I have not seen such messages, but one user had object map related messages before but that was with an older version of Ceph. In that user's case they were harmless if I remember correctly. But I can't tell if this is also the case with your messages. Sorry.

**Comment by elemental-lf** [comment]
I'm going to close this issue as there hasn't been any additional feedback on this.

**Comment by wanthalf** [comment]
No additional feedback has been requested. The issue persists, but it does not seem to be critical for the backups. I tried to raise the question in the Ceph mailing list, but I got no response. However, I have noticed someone else (and more competent than me) to discuss the same issue with the developers recently. Let't hope they will come to some conclusion.

**Comment by elemental-lf** [comment]
@wanthalf thanks for the update, it's appreciated.
