### ISSUE TITLE
Modify helm chart to have URL dependencies instead of named

### ISSUE THREAD

**Issue by SerialVelocity** [elemental-lf/benji#89]
When trying to use deployment software such as https://github.com/fluxcd/helm-operator, it can't use the benji chart without extra configuration as the chart expects a repo called `@stable` to exist.

Most helm charts use urls. e.g.:
https://github.com/helm/charts/blob/92be1ddfc5a242eacae8c34a4401eb1561240d74/stable/prometheus-operator/requirements.yaml
https://github.com/helm/charts/blob/92be1ddfc5a242eacae8c34a4401eb1561240d74/stable/owncloud/requirements.yaml

Could you switch out `@stable` for `https://kubernetes-charts.storage.googleapis.com/`?

**Comment by elemental-lf** [comment]
I will look into this, but at first glance it shouldn't be a problem to change that.
