### ISSUE TITLE
Filter expressions slow / triple expressions fail

### ISSUE THREAD

**Issue by olifre** [elemental-lf/benji#9]
Using:
```
benji -m ls 'snapshot_name == "b-2018-10-31T01:22:09+0100" and name == "somehost.example.com-disk1" and valid == True'
```
yields:
```
ERROR: Invalid filter expression snapshot_name == "b-2018-10-31T01:22:09+0100" and name == "somehost.example.com-disk1" and valid == True (2).
```

Interestingly, this works fine:
```
benji -m ls '(snapshot_name == "b-2018-10-31T01:22:09+0100" and name == "somehost.example.com-disk1") and valid == True'
```
but executes for about _half a minute_. 

The same slowness is observed if just brackets are added:
```
benji -m ls '(snapshot_name == "b-2018-10-31T01:22:09+0100" and name == "somehost.example.com-disk1")'
```

As compared to e.g.
```
benji -m ls 'snapshot_name == "b-2018-10-31T01:22:09+0100" and name == "somehost.example.com-disk1"' | jq -r '.versions[] | select(.valid == true)'
```
which executes in about 2 seconds on the same host (including python interpreter startup, activating the virtualenv etc.). 

It seems that:
- Having three logically combined expressions is not supported (yet). Is this expected?
- Adding brackets triggers extremely slow runtime. Does this cause a full table scan? Even then, I would not expect that. 

Using `jq`, however, is a viable workaround for my usecase. 

Nota bene: The filter system is a really cool feature! :+1:

**Comment by elemental-lf** [comment]
I just pushed https://github.com/elemental-lf/benji/commit/4d085d93af50b7bf0df2c55dd4a435613ae585d3 which makes _and_ and _or_ multiary operators as they should be. I'm still not sure if I'm using `infixNotation` of pyparsing correctly. Could you please test it in your environment?
The slowness seems to be a different issue which I still need to investigate. Stay tuned.

**Comment by elemental-lf** [comment]
Hmm, would've been nice if this was included in the main documentation of pyparsing:
>     Note: if you define a deep operator list, you may see performance
>     issues when using infixNotation. See
>     :class:`ParserElement.enablePackrat` for a mechanism to potentially
>     improve your parser performance.
I just pushed https://github.com/elemental-lf/benji/commit/0923da978afb9e9637afec32e9dfbb1daf76a749 which enables Packrat parsing. With this the parsing performance of the expression in parentheses is only a little bit longer than without them.

**Comment by olifre** [comment]
Perfect, that did the trick, both multiary expressions work now and performance using braces is useable. I agree something like that should have been included in the main documentation. Sadly I'm also not an expert of most Python packages, otherwise I'd have proposed something. 
Thanks for digging and finding the remedy! 

So from my point of view, we could close the issue, unless you want to keep it open until a "release" with the fix has happened? I'm currently tracking master anyways :wink: .

**Comment by elemental-lf** [comment]
I'll close this issue. Thank you for testing!
