### ISSUE TITLE
Build failing and not pushing to docker

### ISSUE THREAD

**Issue by SerialVelocity** [elemental-lf/benji#92]
It looks like the build is failing for master so it is no longer being pushed to DockerHub.

Looks like it may be this issue:
https://github.com/pypa/setuptools/issues/2355#issuecomment-684961440

P.S. Could you cut a new release with the new Rook RBD support once this is fixed? :)

**Comment by elemental-lf** [comment]
Yeah, I've seen the builds failing. I'm not really sure what is happening and I can't reproduce it locally :(
See [here](https://travis-ci.org/github/elemental-lf/benji/jobs/723536659) for details. It seems that the installation of `ruamel.yaml` is failing but if I try this locally with the same versions for `ruamel.yaml`, `setuptools` and `pip` and Python 3.8.5 it works fine. Travis CI has Python 3.8.0, maybe that's the difference. If you could take a look, I'd appreciate that. Maybe you've got an idea.

**Comment by SerialVelocity** [comment]
Did you try the workaround listed in that issue?
Set up this environment variable:
```
export SETUPTOOLS_USE_DISTUTILS="stdlib"
```

It looks like 8 hours ago a fix was merged into `setuptools v50.2.0`. Maybe try that first?

**Comment by elemental-lf** [comment]
@SerialVelocity Thanks, that did the trick! Travis CI is still working on the tests and will hopefully publish the container images for `0.10.0` after that.
