### ISSUE TITLE
problem in benji database-init

### ISSUE THREAD

**Issue by KubeCirrus** [elemental-lf/benji#99]
I tried everything and on multiple machines and different installations the same error pops-up every time.  Where is the benji.yaml file I can't find it.

# benji database-init
{"event": "Uncaught exception", "level": "error", "timestamp": 1610227868.582149, "file": "/usr/local/benji/lib64/python3.6/site-packages/benji/logging.py", "line": 142, "function": "_handle_exception", "process": 30887, "thread_name": "MainThread", "thread_id": 139704085325632, "exception": "Traceback (most recent call last):\n  File \"/usr/local/benji/bin/benji\", line 8, in <module>\n    sys.exit(main())\n  File \"/usr/local/benji/lib64/python3.6/site-packages/benji/scripts/benji.py\", line 306, in main\n    config = Config()\n  File \"/usr/local/benji/lib64/python3.6/site-packages/benji/config.py\", line 156, in __init__\n    ', '.join(sources)))\nbenji.exception.ConfigurationError: No configuration file found in the default places (/etc/benji.yaml, /etc/benji/benji.yaml, /root/.benji.yaml, /root/benji.yaml)."}

Even if I replicate or create a new file named benji.yaml it throws other errors like 

sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file

**Comment by olifre** [comment]
@Bcouddot After adding a `benji.yaml`, which database location did you specify inside? Does the location exist? 
For example, if you set:
```YAML
databaseEngine: sqlite:////some/absolute/path/db.sqlite
```
you need to ensure that the directory `/some/absolute/path` exists before running `benji database-init`.

**Comment by KubeCirrus** [comment]
Thanks olifre it worked
